export interface Agent {
  id: string;
  name: string;
  nameLocal?: string;
  description: string;
  lat: number;
  lng: number;
  type: AgentType;
  continent: Continent;
  country: string;
  city: string;
  foundedYear: number;
  popularity: number; // 1-100
  capabilities: string[];
  model?: string;
  contextWindow?: number;
  website?: string;
  avatarUrl?: string;
}

export type AgentType = 
  | 'coding'
  | 'research'
  | 'creative'
  | 'productivity'
  | 'analysis'
  | 'assistant'
  | 'security'
  | 'automation';

export type Continent = 
  | 'Asia'
  | 'Europe'
  | 'North America'
  | 'South America'
  | 'Africa'
  | 'Oceania';

export const agentTypeColors: Record<AgentType, string> = {
  'coding': '#00FF00',
  'research': '#00BFFF',
  'creative': '#FF69B4',
  'productivity': '#FFD700',
  'analysis': '#9370DB',
  'assistant': '#FF6347',
  'security': '#FF4500',
  'automation': '#32CD32',
};

export const agentTypeLabels: Record<AgentType, string> = {
  'coding': '编程助手',
  'research': '研究助手',
  'creative': '创意助手',
  'productivity': '效率助手',
  'analysis': '分析助手',
  'assistant': '通用助手',
  'security': '安全助手',
  'automation': '自动化助手',
};

export const continentLabels: Record<Continent, string> = {
  'Asia': '亚洲',
  'Europe': '欧洲',
  'North America': '北美洲',
  'South America': '南美洲',
  'Africa': '非洲',
  'Oceania': '大洋洲',
};

// Virtual AI Agents dataset - global distribution
export const agents: Agent[] = [
  // Asia
  {
    id: 'claude-asia',
    name: 'Claude Asia Hub',
    nameLocal: '克劳德亚洲中心',
    description: 'Anthropic Claude 系列旗舰 AI 助手，专注于推理、安全和有害性规避。',
    lat: 35.6762,
    lng: 139.6503,
    type: 'assistant',
    continent: 'Asia',
    country: 'Japan',
    city: 'Tokyo',
    foundedYear: 2023,
    popularity: 98,
    capabilities: ['代码生成', '文案撰写', '数据分析', '推理思考'],
    model: 'Claude 3.5 Sonnet',
    contextWindow: 200000,
    website: 'https://claude.ai',
  },
  {
    id: 'gemini-asia',
    name: 'Gemini Ultra',
    nameLocal: '双子座超星',
    description: 'Google DeepMind 多模态 AI，支持文本、图像、视频理解。',
    lat: 31.2304,
    lng: 121.4737,
    type: 'research',
    continent: 'Asia',
    country: 'China',
    city: 'Shanghai',
    foundedYear: 2023,
    popularity: 95,
    capabilities: ['多模态理解', '长文本处理', '代码生成', '创意写作'],
    model: 'Gemini 1.5 Pro',
    contextWindow: 2000000,
    website: 'https://gemini.google.com',
  },
  {
    id: 'qwen-global',
    name: 'Qwen Max',
    nameLocal: '通义千问',
    description: '阿里巴巴开源大模型系列，支持长上下文和代码能力。',
    lat: 30.5728,
    lng: 114.2794,
    type: 'coding',
    continent: 'Asia',
    country: 'China',
    city: 'Wuhan',
    foundedYear: 2023,
    popularity: 90,
    capabilities: ['代码补全', '智能问答', '创意生成', '多语言支持'],
    model: 'Qwen 2.5 Max',
    contextWindow: 131072,
    website: 'https://qwen.ai',
  },
  {
    id: 'ernie-asia',
    name: 'ERNIE Bot',
    nameLocal: '文心一言',
    description: '百度生成式 AI 产品，知识增强大语言模型。',
    lat: 39.9042,
    lng: 116.4074,
    type: 'assistant',
    continent: 'Asia',
    country: 'China',
    city: 'Beijing',
    foundedYear: 2023,
    popularity: 88,
    capabilities: ['知识问答', '文案创作', '代码生成', '图像理解'],
    model: 'ERNIE 4.0',
    contextWindow: 32000,
    website: 'https://yiyan.baidu.com',
  },
  {
    id: 'kimi-asia',
    name: 'Kimi',
    nameLocal: '月之暗面',
    description: '月之暗面公司出品的超长上下文 AI 助手。',
    lat: 22.5431,
    lng: 114.0579,
    type: 'productivity',
    continent: 'Asia',
    country: 'China',
    city: 'Shenzhen',
    foundedYear: 2023,
    popularity: 92,
    capabilities: ['超长上下文', '文件分析', '网页解析'],
    contextWindow: 1280000,
    website: 'https://kimi.moonshot.cn',
  },
  {
    id: 'copilot-japan',
    name: 'GitHub Copilot',
    nameLocal: '微软copilot',
    description: 'AI 编程助手，集成于 VS Code 等主流 IDE。',
    lat: 34.6937,
    lng: 135.5023,
    type: 'coding',
    continent: 'Asia',
    country: 'Japan',
    city: 'Osaka',
    foundedYear: 2021,
    popularity: 97,
    capabilities: ['代码补全', '代码解释', 'Bug修复', '单元测试'],
    model: 'OpenAI Codex',
    contextWindow: 8192,
    website: 'https://github.com/features/copilot',
  },
  {
    id: 'cursor-asia',
    name: 'Cursor',
    nameLocal: '光标',
    description: 'AI 驱动的代码编辑器，基于 VS Code 构建。',
    lat: 25.0330,
    lng: 121.5654,
    type: 'coding',
    continent: 'Asia',
    country: 'Taiwan',
    city: 'Taipei',
    foundedYear: 2023,
    popularity: 94,
    capabilities: ['代码补全', '智能编辑', '代码重构', '对话编程'],
    model: 'GPT-4 + Claude',
    contextWindow: 128000,
    website: 'https://cursor.sh',
  },

  // Europe
  {
    id: 'claude-europe',
    name: 'Claude Enterprise',
    nameLocal: '克劳德企业版',
    description: 'Anthropic 企业级 AI 助手，强化安全和隐私保护。',
    lat: 48.8566,
    lng: 2.3522,
    type: 'assistant',
    continent: 'Europe',
    country: 'France',
    city: 'Paris',
    foundedYear: 2023,
    popularity: 96,
    capabilities: ['企业安全', '代码生成', '长文档分析', '多语言支持'],
    model: 'Claude 3 Opus',
    contextWindow: 200000,
    website: 'https://claude.ai',
  },
  {
    id: 'mistral-europe',
    name: 'Mistral Large',
    nameLocal: 'Mistral大模型',
    description: '法国 AI 初创公司 Mistral 的旗舰大语言模型。',
    lat: 48.8566,
    lng: 2.3522,
    type: 'research',
    continent: 'Europe',
    country: 'France',
    city: 'Paris',
    foundedYear: 2023,
    popularity: 88,
    capabilities: ['代码生成', '推理能力', '多语言', '长上下文'],
    model: 'Mistral Large 2',
    contextWindow: 128000,
    website: 'https://mistral.ai',
  },
  {
    id: 'gemini-europe',
    name: 'DeepMind Europe',
    nameLocal: 'DeepMind欧洲',
    description: 'Google DeepMind 欧洲研发中心，专注 AI 安全和研究。',
    lat: 51.5074,
    lng: -0.1278,
    type: 'research',
    continent: 'Europe',
    country: 'UK',
    city: 'London',
    foundedYear: 2010,
    popularity: 99,
    capabilities: ['强化学习', 'AlphaFold', 'AI安全', '多模态'],
    model: 'Gemini 1.5 Ultra',
    contextWindow: 2000000,
    website: 'https://deepmind.google',
  },
  {
    id: 'phi-europe',
    name: 'Phi-4',
    nameLocal: 'Phi-4',
    description: 'Microsoft 小语言模型系列，高效且高质量。',
    lat: 52.5200,
    lng: 13.4050,
    type: 'coding',
    continent: 'Europe',
    country: 'Germany',
    city: 'Berlin',
    foundedYear: 2023,
    popularity: 85,
    capabilities: ['代码生成', '指令遵循', '数学推理', '高效推理'],
    model: 'Phi-4',
    contextWindow: 16000,
    website: 'https://azure.microsoft.com',
  },
  {
    id: 'le-chat-europe',
    name: 'Le Chat',
    nameLocal: 'Le Chat',
    description: 'Mistral AI 的对话助手，欧盟本土 AI 替代方案。',
    lat: 45.7640,
    lng: 4.8357,
    type: 'assistant',
    continent: 'Europe',
    country: 'France',
    city: 'Lyon',
    foundedYear: 2023,
    popularity: 82,
    capabilities: ['对话生成', '代码帮助', '文档分析', '创意写作'],
    model: 'Mistral Small',
    contextWindow: 128000,
    website: 'https://chat.mistral.ai',
  },

  // North America
  {
    id: 'gpt4-us',
    name: 'GPT-4',
    nameLocal: 'GPT-4',
    description: 'OpenAI 旗舰大语言模型，多模态理解能力。',
    lat: 37.7749,
    lng: -122.4194,
    type: 'assistant',
    continent: 'North America',
    country: 'USA',
    city: 'San Francisco',
    foundedYear: 2023,
    popularity: 100,
    capabilities: ['文本生成', '代码编写', '图像理解', 'API调用'],
    model: 'GPT-4',
    contextWindow: 128000,
    website: 'https://openai.com',
  },
  {
    id: 'gpt4o-us',
    name: 'GPT-4o',
    nameLocal: 'GPT-4o',
    description: 'OpenAI 最新多模态模型，实时语音和视觉能力。',
    lat: 37.7749,
    lng: -122.4194,
    type: 'creative',
    continent: 'North America',
    country: 'USA',
    city: 'San Francisco',
    foundedYear: 2024,
    popularity: 99,
    capabilities: ['实时语音', '视觉理解', '多语言', '极速响应'],
    model: 'GPT-4o',
    contextWindow: 128000,
    website: 'https://openai.com',
  },
  {
    id: 'claude-us',
    name: 'Claude 3.5',
    nameLocal: 'Claude 3.5',
    description: 'Anthropic 最新模型，卓越的推理和代码能力。',
    lat: 37.3861,
    lng: -122.0839,
    type: 'coding',
    continent: 'North America',
    country: 'USA',
    city: 'Mountain View',
    foundedYear: 2023,
    popularity: 97,
    capabilities: ['代码生成', '长文本分析', '推理思考', '有害规避'],
    model: 'Claude 3.5 Sonnet',
    contextWindow: 200000,
    website: 'https://claude.ai',
  },
  {
    id: 'gemini-us',
    name: 'Bard / Gemini',
    nameLocal: 'Bard',
    description: 'Google 对话 AI，现在统一为 Gemini 品牌。',
    lat: 40.7128,
    lng: -74.0060,
    type: 'assistant',
    continent: 'North America',
    country: 'USA',
    city: 'New York',
    foundedYear: 2023,
    popularity: 94,
    capabilities: ['搜索集成', '创意写作', '代码生成', '多模态'],
    model: 'Gemini 1.5 Pro',
    contextWindow: 2000000,
    website: 'https://gemini.google.com',
  },
  {
    id: 'llama-us',
    name: 'Llama 3.1',
    nameLocal: 'Llama 3.1',
    description: 'Meta 开源大模型，可本地部署。',
    lat: 34.0522,
    lng: -118.2437,
    type: 'research',
    continent: 'North America',
    country: 'USA',
    city: 'Los Angeles',
    foundedYear: 2023,
    popularity: 93,
    capabilities: ['开源', '本地部署', '多语言', '指令微调'],
    model: 'Llama 3.1 405B',
    contextWindow: 128000,
    website: 'https://ai.meta.com/llama',
  },
  {
    id: 'copilot-us',
    name: 'Microsoft Copilot',
    nameLocal: '微软Copilot',
    description: 'Microsoft 全面 AI 助手，集成 Windows 和 Edge。',
    lat: 47.6062,
    lng: -122.3321,
    type: 'productivity',
    continent: 'North America',
    country: 'USA',
    city: 'Seattle',
    foundedYear: 2023,
    popularity: 95,
    capabilities: ['Office集成', '搜索增强', '代码生成', '内容创作'],
    model: 'GPT-4 + Prometheus',
    contextWindow: 128000,
    website: 'https://copilot.microsoft.com',
  },
  {
    id: 'perplexity-us',
    name: 'Perplexity',
    nameLocal: 'Perplexity',
    description: 'AI 驱动的搜索引擎，实时信息检索。',
    lat: 37.7749,
    lng: -122.4194,
    type: 'analysis',
    continent: 'North America',
    country: 'USA',
    city: 'San Francisco',
    foundedYear: 2022,
    popularity: 91,
    capabilities: ['实时搜索', '来源引用', '内容摘要', '追问功能'],
    model: 'GPT-4 + Llama',
    contextWindow: 128000,
    website: 'https://perplexity.ai',
  },
  {
    id: 'claude-team-us',
    name: 'Claude Team',
    nameLocal: 'Claude团队版',
    description: 'Anthropic 团队协作版本，企业级 AI 能力。',
    lat: 32.7767,
    lng: -96.7970,
    type: 'assistant',
    continent: 'North America',
    country: 'USA',
    city: 'Dallas',
    foundedYear: 2024,
    popularity: 86,
    capabilities: ['团队协作', '企业知识库', 'API集成', '审计日志'],
    model: 'Claude 3.5 Enterprise',
    contextWindow: 200000,
    website: 'https://claude.ai',
  },
  {
    id: 'groq-us',
    name: 'Groq',
    nameLocal: 'Groq',
    description: '超快速推理引擎，低延迟 AI 推理。',
    lat: 33.4484,
    lng: -112.0740,
    type: 'analysis',
    continent: 'North America',
    country: 'USA',
    city: 'Phoenix',
    foundedYear: 2024,
    popularity: 84,
    capabilities: ['极速推理', '流式输出', 'API集成', '多模型'],
    model: 'Llama 3 + Mixtral',
    contextWindow: 8192,
    website: 'https://groq.com',
  },
  {
    id: 'cohere-us',
    name: 'Cohere',
    nameLocal: 'Cohere',
    description: '企业级大语言模型，专注安全可靠。',
    lat: 43.6532,
    lng: -79.3832,
    type: 'security',
    continent: 'North America',
    country: 'Canada',
    city: 'Toronto',
    foundedYear: 2019,
    popularity: 83,
    capabilities: ['企业AI', '搜索增强', '文本生成', '安全合规'],
    model: 'Command R+',
    contextWindow: 128000,
    website: 'https://cohere.com',
  },

  // South America
  {
    id: 'sabia-br',
    name: 'Sabia',
    nameLocal: 'Sabia',
    description: '巴西本土大语言模型，专注葡萄牙语。',
    lat: -23.5505,
    lng: -46.6333,
    type: 'assistant',
    continent: 'South America',
    country: 'Brazil',
    city: 'São Paulo',
    foundedYear: 2023,
    popularity: 80,
    capabilities: ['葡萄牙语', '文化理解', '代码生成', '教育辅助'],
    model: 'Sabia 3',
    contextWindow: 32000,
    website: 'https://sabia.ai',
  },
  {
    id: 'alpaca-sa',
    name: 'Alpaca',
    nameLocal: '羊驼',
    description: '开源指令微调模型，学术研究友好。',
    lat: -34.6037,
    lng: -58.3816,
    type: 'research',
    continent: 'South America',
    country: 'Argentina',
    city: 'Buenos Aires',
    foundedYear: 2023,
    popularity: 78,
    capabilities: ['指令遵循', '学术研究', '本地部署', '多语言'],
    model: 'Alpaca',
    contextWindow: 4096,
    website: 'https://crfm.stanford.edu/2023/03/13/alpaca',
  },

  // Africa
  {
    id: 'jumi-ai',
    name: 'Jumi AI',
    nameLocal: 'Jumi AI',
    description: '非洲本土 AI 平台，支持多语种。',
    lat: -1.2921,
    lng: 36.8219,
    type: 'assistant',
    continent: 'Africa',
    country: 'Kenya',
    city: 'Nairobi',
    foundedYear: 2023,
    popularity: 75,
    capabilities: ['多语种', '本地化', '教育辅助', '农业咨询'],
    model: 'Jumi 1.0',
    contextWindow: 8192,
    website: 'https://jumi.ai',
  },
  {
    id: 'kilimo-ai',
    name: 'Kilimo AI',
    nameLocal: 'Kilimo AI',
    description: '聚焦农业的非洲 AI 助手。',
    lat: 6.5244,
    lng: 3.3792,
    type: 'automation',
    continent: 'Africa',
    country: 'Nigeria',
    city: 'Lagos',
    foundedYear: 2024,
    popularity: 72,
    capabilities: ['农业咨询', '天气预测', '作物建议', '市场信息'],
    model: 'Kilimo 1.0',
    contextWindow: 4096,
    website: 'https://kilimo.africa',
  },

  // Oceania
  {
    id: 'ollama-anz',
    name: 'Ollama',
    nameLocal: 'Ollama',
    description: '本地大模型运行框架，Mac/Windows/Linux 支持。',
    lat: -33.8688,
    lng: 151.2093,
    type: 'coding',
    continent: 'Oceania',
    country: 'Australia',
    city: 'Sydney',
    foundedYear: 2023,
    popularity: 89,
    capabilities: ['本地部署', '开源模型', '隐私保护', '多平台'],
    model: 'Llama 3.1 + Mistral',
    contextWindow: 128000,
    website: 'https://ollama.ai',
  },
  {
    id: 'huggingface-oz',
    name: 'Hugging Face',
    nameLocal: '抱抱脸',
    description: '开源 AI 社区和模型托管平台。',
    lat: -37.8136,
    lng: 144.9631,
    type: 'research',
    continent: 'Oceania',
    country: 'Australia',
    city: 'Melbourne',
    foundedYear: 2016,
    popularity: 96,
    capabilities: ['模型托管', '模型下载', 'Spaces', 'Inference API'],
    model: 'Multiple',
    contextWindow: 0,
    website: 'https://huggingface.co',
  },
];
