export interface Museum {
  id: string;
  name: string;
  nameLocal?: string;
  description: string;
  lat: number;
  lng: number;
  type: MuseumType;
  continent: Continent;
  country: string;
  city: string;
  foundedYear: number;
  popularity: number; // 1-100
  annualVisitors?: number;
  highlights: string[];
  openingHours: string;
  website?: string;
  imageUrl?: string;
}

export type MuseumType = 
  | 'art'
  | 'history'
  | 'science'
  | 'natural-history'
  | 'archaeology'
  | 'technology'
  | 'cultural'
  | 'military'
  | 'maritime'
  | 'specialized';

export type Continent = 
  | 'Asia'
  | 'Europe'
  | 'North America'
  | 'South America'
  | 'Africa'
  | 'Oceania';

export const museumTypeColors: Record<MuseumType, string> = {
  'art': '#E8E8E8',
  'history': '#C0C0C0',
  'science': '#A8D8FF',
  'natural-history': '#98FB98',
  'archaeology': '#DDA0DD',
  'technology': '#00FFFF',
  'cultural': '#FFB6C1',
  'military': '#808080',
  'maritime': '#87CEEB',
  'specialized': '#D8BFD8',
};

export const museumTypeLabels: Record<MuseumType, string> = {
  'art': '艺术博物馆',
  'history': '历史博物馆',
  'science': '科学博物馆',
  'natural-history': '自然历史博物馆',
  'archaeology': '考古博物馆',
  'technology': '科技博物馆',
  'cultural': '文化博物馆',
  'military': '军事博物馆',
  'maritime': '海事博物馆',
  'specialized': '专题博物馆',
};

export const continentLabels: Record<Continent, string> = {
  'Asia': '亚洲',
  'Europe': '欧洲',
  'North America': '北美洲',
  'South America': '南美洲',
  'Africa': '非洲',
  'Oceania': '大洋洲',
};

// Comprehensive museum dataset based on real world data
export const museums: Museum[] = [
  // Europe
  {
    id: 'louvre',
    name: 'Louvre Museum',
    nameLocal: '卢浮宫',
    description: '世界上最大的艺术博物馆，拥有超过38万件藏品，包括蒙娜丽莎和胜利女神像。',
    lat: 48.8606,
    lng: 2.3376,
    type: 'art',
    continent: 'Europe',
    country: 'France',
    city: 'Paris',
    foundedYear: 1793,
    popularity: 100,
    annualVisitors: 9600000,
    highlights: ['蒙娜丽莎', '胜利女神像', '米洛的维纳斯', '汉谟拉比法典'],
    openingHours: '周一、周四、周六、周日 9:00-18:00；周三、周五 9:00-21:45',
    website: 'https://www.louvre.fr',
  },
  {
    id: 'british-museum',
    name: 'British Museum',
    nameLocal: '大英博物馆',
    description: '世界上历史最悠久、规模最宏伟的综合性博物馆之一，收藏约800万件文物。',
    lat: 51.5194,
    lng: -0.1270,
    type: 'history',
    continent: 'Europe',
    country: 'United Kingdom',
    city: 'London',
    foundedYear: 1753,
    popularity: 98,
    annualVisitors: 5820000,
    highlights: ['罗塞塔石碑', '帕特农神庙雕塑', '埃及木乃伊', '刘易斯棋子'],
    openingHours: '每日 10:00-17:00',
    website: 'https://www.britishmuseum.org',
  },
  {
    id: 'vatican-museums',
    name: 'Vatican Museums',
    nameLocal: '梵蒂冈博物馆',
    description: '世界上最伟大的艺术收藏之一，包括西斯廷教堂和拉斐尔房间。',
    lat: 41.9065,
    lng: 12.4536,
    type: 'art',
    continent: 'Europe',
    country: 'Vatican City',
    city: 'Vatican City',
    foundedYear: 1506,
    popularity: 97,
    annualVisitors: 6756000,
    highlights: ['西斯廷教堂天顶画', '拉斐尔房间', '拉奥孔群像', '贝尔韦代雷的阿波罗'],
    openingHours: '周一至周六 9:00-18:00',
    website: 'https://www.museivaticani.va',
  },
  {
    id: 'hermitage',
    name: 'State Hermitage Museum',
    nameLocal: '冬宫博物馆',
    description: '俄罗斯最大的博物馆，拥有超过300万件藏品，是世界四大博物馆之一。',
    lat: 59.9398,
    lng: 30.3146,
    type: 'art',
    continent: 'Europe',
    country: 'Russia',
    city: 'Saint Petersburg',
    foundedYear: 1764,
    popularity: 95,
    annualVisitors: 4956000,
    highlights: ['达芬奇的圣母像', '伦勃朗作品', '孔雀钟', '冬宫建筑本身'],
    openingHours: '周二、周四、周六、周日 10:30-18:00；周三、周五 10:30-21:00',
    website: 'https://www.hermitagemuseum.org',
  },
  {
    id: 'prado',
    name: 'Museo del Prado',
    nameLocal: '普拉多博物馆',
    description: '西班牙最重要的国家艺术博物馆，收藏欧洲最完整的绘画作品。',
    lat: 40.4138,
    lng: -3.6921,
    type: 'art',
    continent: 'Europe',
    country: 'Spain',
    city: 'Madrid',
    foundedYear: 1819,
    popularity: 94,
    annualVisitors: 3300000,
    highlights: ['委拉斯开兹的宫娥', '戈雅的黑色绘画', '博斯的人间乐园'],
    openingHours: '周一至周六 10:00-20:00；周日 10:00-19:00',
    website: 'https://www.museodelprado.es',
  },
  {
    id: 'rijksmuseum',
    name: 'Rijksmuseum',
    nameLocal: '荷兰国立博物馆',
    description: '荷兰最大的博物馆，收藏荷兰黄金时代的杰作。',
    lat: 52.3600,
    lng: 4.8852,
    type: 'art',
    continent: 'Europe',
    country: 'Netherlands',
    city: 'Amsterdam',
    foundedYear: 1800,
    popularity: 92,
    annualVisitors: 2700000,
    highlights: ['伦勃朗的夜巡', '维米尔的倒牛奶的女仆', '代尔夫特蓝陶'],
    openingHours: '每日 9:00-17:00',
    website: 'https://www.rijksmuseum.nl',
  },
  {
    id: 'uffizi',
    name: 'Uffizi Gallery',
    nameLocal: '乌菲兹美术馆',
    description: '意大利最重要的美术馆之一，拥有文艺复兴时期最杰出的艺术收藏。',
    lat: 43.7687,
    lng: 11.2559,
    type: 'art',
    continent: 'Europe',
    country: 'Italy',
    city: 'Florence',
    foundedYear: 1581,
    popularity: 93,
    annualVisitors: 2230000,
    highlights: ['波提切利的维纳斯诞生', '达芬奇的天使报喜', '卡拉瓦乔的美杜莎'],
    openingHours: '周二至周日 8:15-18:50',
    website: 'https://www.uffizi.it',
  },
  {
    id: 'deutsches-museum',
    name: 'Deutsches Museum',
    nameLocal: '德意志博物馆',
    description: '世界上最大的科学技术博物馆，展示从自然科学到技术的各个领域。',
    lat: 48.1299,
    lng: 11.5833,
    type: 'science',
    continent: 'Europe',
    country: 'Germany',
    city: 'Munich',
    foundedYear: 1903,
    popularity: 88,
    annualVisitors: 1500000,
    highlights: ['第一台柴油发动机', '原子物理展', '采矿展区', '航空航天展'],
    openingHours: '每日 9:00-17:00',
    website: 'https://www.deutsches-museum.de',
  },
  {
    id: 'acropolis-museum',
    name: 'Acropolis Museum',
    nameLocal: '卫城博物馆',
    description: '收藏来自雅典卫城的文物，展示古希腊文明的辉煌。',
    lat: 37.9686,
    lng: 23.7286,
    type: 'archaeology',
    continent: 'Europe',
    country: 'Greece',
    city: 'Athens',
    foundedYear: 2009,
    popularity: 87,
    annualVisitors: 1800000,
    highlights: ['帕特农神庙浮雕', '女像柱原件', '古风时期雕塑'],
    openingHours: '周一 8:00-16:00；周二至周日 8:00-20:00',
    website: 'https://www.theacropolismuseum.gr',
  },
  {
    id: 'natural-history-london',
    name: 'Natural History Museum',
    nameLocal: '伦敦自然历史博物馆',
    description: '世界领先的自然历史博物馆，拥有超过8000万件标本。',
    lat: 51.4967,
    lng: -0.1764,
    type: 'natural-history',
    continent: 'Europe',
    country: 'United Kingdom',
    city: 'London',
    foundedYear: 1881,
    popularity: 91,
    annualVisitors: 5200000,
    highlights: ['霍普恐龙', '渡渡鸟标本', '达尔文中心', '矿物展厅'],
    openingHours: '每日 10:00-17:50',
    website: 'https://www.nhm.ac.uk',
  },
  
  // Asia
  {
    id: 'palace-museum',
    name: 'Palace Museum',
    nameLocal: '故宫博物院',
    description: '位于紫禁城内，是中国最大的古代文化艺术博物馆，藏品超过180万件。',
    lat: 39.9163,
    lng: 116.3972,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Beijing',
    foundedYear: 1925,
    popularity: 99,
    annualVisitors: 17000000,
    highlights: ['紫禁城建筑群', '清明上河图', '青铜器', '瓷器珍藏'],
    openingHours: '周二至周日 8:30-17:00',
    website: 'https://www.dpm.org.cn',
  },
  {
    id: 'national-museum-china',
    name: 'National Museum of China',
    nameLocal: '中国国家博物馆',
    description: '世界上单体建筑面积最大的博物馆，展示中华五千年文明史。',
    lat: 39.9050,
    lng: 116.3979,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Beijing',
    foundedYear: 2003,
    popularity: 96,
    annualVisitors: 8610000,
    highlights: ['后母戊鼎', '四羊方尊', '击鼓说唱俑', '金缕玉衣'],
    openingHours: '周二至周日 9:00-17:00',
    website: 'https://www.chnmuseum.cn',
  },
  {
    id: 'shanghai-museum',
    name: 'Shanghai Museum',
    nameLocal: '上海博物馆',
    description: '中国四大博物馆之一，以中国古代艺术品收藏闻名。',
    lat: 31.2293,
    lng: 121.4750,
    type: 'art',
    continent: 'Asia',
    country: 'China',
    city: 'Shanghai',
    foundedYear: 1952,
    popularity: 89,
    annualVisitors: 2100000,
    highlights: ['青铜器馆', '陶瓷馆', '书画馆', '玉器馆'],
    openingHours: '周二至周日 9:00-17:00',
    website: 'https://www.shanghaimuseum.net',
  },
  {
    id: 'tokyo-national-museum',
    name: 'Tokyo National Museum',
    nameLocal: '东京国立博物馆',
    description: '日本最古老、规模最大的博物馆，收藏亚洲艺术珍品。',
    lat: 35.7189,
    lng: 139.7766,
    type: 'art',
    continent: 'Asia',
    country: 'Japan',
    city: 'Tokyo',
    foundedYear: 1872,
    popularity: 90,
    annualVisitors: 2200000,
    highlights: ['法隆寺宝物馆', '日本刀剑', '浮世绘', '佛教艺术'],
    openingHours: '周二至周日 9:30-17:00',
    website: 'https://www.tnm.jp',
  },
  {
    id: 'national-museum-korea',
    name: 'National Museum of Korea',
    nameLocal: '韩国国立中央博物馆',
    description: '韩国最大的博物馆，展示韩国和亚洲的历史文化。',
    lat: 37.5238,
    lng: 126.9802,
    type: 'history',
    continent: 'Asia',
    country: 'South Korea',
    city: 'Seoul',
    foundedYear: 1945,
    popularity: 86,
    annualVisitors: 3500000,
    highlights: ['金冠', '高丽青瓷', '百济遗物', '佛教艺术'],
    openingHours: '周二至周日 10:00-18:00；周三、周六至21:00',
    website: 'https://www.museum.go.kr',
  },
  {
    id: 'national-museum-india',
    name: 'National Museum',
    nameLocal: '印度国家博物馆',
    description: '印度最大的博物馆之一，收藏从史前到现代的印度文化遗产。',
    lat: 28.6117,
    lng: 77.2195,
    type: 'history',
    continent: 'Asia',
    country: 'India',
    city: 'New Delhi',
    foundedYear: 1949,
    popularity: 82,
    annualVisitors: 1200000,
    highlights: ['印度河文明遗物', '佛教艺术', '细密画', '纺织品'],
    openingHours: '周二至周日 10:00-18:00',
    website: 'https://www.nationalmuseumindia.gov.in',
  },
  {
    id: 'terracotta-army',
    name: 'Museum of Qin Terracotta Warriors',
    nameLocal: '秦始皇兵马俑博物馆',
    description: '世界第八大奇迹，展示秦始皇陵兵马俑坑的宏伟规模。',
    lat: 34.3847,
    lng: 109.2785,
    type: 'archaeology',
    continent: 'Asia',
    country: 'China',
    city: "Xi'an",
    foundedYear: 1979,
    popularity: 95,
    annualVisitors: 8500000,
    highlights: ['一号坑', '二号坑', '铜车马', '将军俑'],
    openingHours: '3月-11月 8:30-18:00；12月-2月 8:30-17:30',
    website: 'http://www.bmy.com.cn',
  },

  // 更多中国博物馆
  {
    id: 'nanjing-museum',
    name: 'Nanjing Museum',
    nameLocal: '南京博物院',
    description: '中国三大博物院之一，藏品超过40万件。',
    lat: 32.0254,
    lng: 118.7882,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Nanjing',
    foundedYear: 1933,
    popularity: 88,
    annualVisitors: 3000000,
    highlights: ['金缕玉衣', '竹林七贤砖画', '明代服饰'],
    openingHours: '周二至周日 9:00-17:00',
    website: 'https://www.njmuseum.com',
  },
  {
    id: 'shaanxi-history-museum',
    name: 'Shaanxi History Museum',
    nameLocal: '陕西历史博物馆',
    description: '中国第一座大型现代化国家级博物馆，藏品171万余件。',
    lat: 34.7466,
    lng: 108.9537,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: "Xi'an",
    foundedYear: 1991,
    popularity: 90,
    annualVisitors: 2800000,
    highlights: ['兽首玛瑙杯', '鎏金舞马衔杯纹银壶', '唐三彩'],
    openingHours: '周二至周日 9:00-17:30',
    website: 'https://www.sxhm.com',
  },
  {
    id: 'hunan-museum',
    name: 'Hunan Museum',
    nameLocal: '湖南省博物馆',
    description: '展示湘楚文化的大型综合性博物馆。',
    lat: 28.2131,
    lng: 112.9913,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Changsha',
    foundedYear: 1951,
    popularity: 87,
    annualVisitors: 2000000,
    highlights: ['马王堆汉墓文物', '素纱襌衣', 'T形帛画'],
    openingHours: '周二至周日 9:00-17:00',
    website: 'https://www.hnmuseum.com',
  },
  {
    id: 'henan-museum',
    name: 'Henan Museum',
    nameLocal: '河南博物院',
    description: '中国历史上建立最早的博物馆之一，藏品14万多件。',
    lat: 34.7468,
    lng: 113.6254,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Zhengzhou',
    foundedYear: 1927,
    popularity: 86,
    annualVisitors: 1800000,
    highlights: ['莲鹤方壶', '贾湖骨笛', '武则天金简'],
    openingHours: '周二至周日 9:00-17:00',
    website: 'https://www.chnmus.net',
  },
  {
    id: 'sichuan-museum',
    name: 'Sichuan Museum',
    nameLocal: '四川博物院',
    description: '西南地区最大的综合性博物馆。',
    lat: 30.6691,
    lng: 104.0658,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Chengdu',
    foundedYear: 1941,
    popularity: 84,
    annualVisitors: 1500000,
    highlights: ['张大千书画', '巴蜀青铜器', '汉代画像砖'],
    openingHours: '周二至周日 9:00-17:00',
    website: 'https://www.scmuseum.cn',
  },
  {
    id: 'guangzhou-museum',
    name: 'Guangzhou Museum',
    nameLocal: '广州博物馆',
    description: '华南地区著名的综合性博物馆。',
    lat: 23.1291,
    lng: 113.2644,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Guangzhou',
    foundedYear: 1929,
    popularity: 82,
    annualVisitors: 1200000,
    highlights: ['广州历史陈列', '海丝文化展', '明清瓷器'],
    openingHours: '周二至周日 9:00-17:30',
    website: 'https://www.guangzhoumuseum.cn',
  },
  {
    id: 'yunnan-museum',
    name: 'Yunnan Museum',
    nameLocal: '云南省博物馆',
    description: '展示云南多元文化的大型博物馆。',
    lat: 25.0453,
    lng: 102.7094,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Kunming',
    foundedYear: 1941,
    popularity: 80,
    annualVisitors: 1000000,
    highlights: ['滇青铜器', '彝族服饰', '纳西东巴文化'],
    openingHours: '周二至周日 9:00-17:00',
    website: 'https://www.ynmuseum.org',
  },
  {
    id: 'shandong-museum',
    name: 'Shandong Museum',
    nameLocal: '山东博物馆',
    description: '新中国成立后建立的大型综合性博物馆。',
    lat: 36.6512,
    lng: 117.1205,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Jinan',
    foundedYear: 1952,
    popularity: 83,
    annualVisitors: 1100000,
    highlights: ['鲁国大玉璧', '东平汉墓壁画', '红陶兽形壶'],
    openingHours: '周二至周日 9:00-17:00',
    website: 'https://www.sdmuseum.com',
  },
  {
    id: 'liaoning-museum',
    name: 'Liaoning Museum',
    nameLocal: '辽宁省博物馆',
    description: '东北地区最大的综合性博物馆。',
    lat: 41.8082,
    lng: 123.4328,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Shenyang',
    foundedYear: 1949,
    popularity: 81,
    annualVisitors: 1000000,
    highlights: ['红山文化玉器', '辽代瓷器', '清代宫廷用品'],
    openingHours: '周二至周日 9:00-16:30',
    website: 'https://www.lnmuseum.com.cn',
  },
  {
    id: 'hubei-museum',
    name: 'Hubei Museum',
    nameLocal: '湖北省博物馆',
    description: '展示荆楚文化的重要基地。',
    lat: 30.5386,
    lng: 114.3063,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Wuhan',
    foundedYear: 1953,
    popularity: 85,
    annualVisitors: 1300000,
    highlights: ['曾侯乙编钟', '越王勾践剑', '元青花四爱图梅瓶'],
    openingHours: '周二至周日 9:00-17:00',
    website: 'https://www.hbmuseum.com.cn',
  },
  {
    id: 'zhejiang-museum',
    name: 'Zhejiang Museum',
    nameLocal: '浙江省博物馆',
    description: '展示浙江历史文化的重要窗口。',
    lat: 30.2526,
    lng: 120.1519,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Hangzhou',
    foundedYear: 1929,
    popularity: 84,
    annualVisitors: 1200000,
    highlights: ['河姆渡文化遗物', '越窑青瓷', '西湖织锦'],
    openingHours: '周二至周日 9:00-17:00',
    website: 'https://www.zjmuseum.com.cn',
  },
  {
    id: 'anhui-museum',
    name: 'Anhui Museum',
    nameLocal: '安徽博物院',
    description: '展示徽州文化的重要博物馆。',
    lat: 31.8214,
    lng: 117.2321,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Hefei',
    foundedYear: 1956,
    popularity: 79,
    annualVisitors: 800000,
    highlights: ['徽州三雕', '楚大鼎', '新安画派'],
    openingHours: '周二至周日 9:00-17:00',
    website: 'https://www.ahm.cn',
  },
  {
    id: 'fujian-museum',
    name: 'Fujian Museum',
    nameLocal: '福建博物院',
    description: '福建省唯一的省级综合性博物馆。',
    lat: 26.1045,
    lng: 119.2965,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Fuzhou',
    foundedYear: 1953,
    popularity: 78,
    annualVisitors: 750000,
    highlights: ['福建古代外销瓷', '闽南古建筑', '客家文化'],
    openingHours: '周二至周日 9:00-17:00',
    website: 'https://www.fjbwy.com',
  },
  {
    id: 'jiangxi-museum',
    name: 'Jiangxi Museum',
    nameLocal: '江西省博物馆',
    description: '展示江西历史文化的重要窗口。',
    lat: 28.6820,
    lng: 115.8581,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Nanchang',
    foundedYear: 1953,
    popularity: 77,
    annualVisitors: 700000,
    highlights: ['景德镇瓷器', '海昏侯墓文物', '赣傩文化'],
    openingHours: '周二至周日 9:00-17:00',
    website: 'https://www.jxmuseum.cn',
  },
  {
    id: 'shanxi-museum',
    name: 'Shaanxi Museum of Fine Arts',
    nameLocal: '西安美术学院美术博物馆',
    description: '集收藏、研究、展示于一体的专业博物馆。',
    lat: 34.2590,
    lng: 108.9456,
    type: 'art',
    continent: 'Asia',
    country: 'China',
    city: "Xi'an",
    foundedYear: 2000,
    popularity: 75,
    annualVisitors: 500000,
    highlights: ['历代书画', '民间美术', '雕塑艺术'],
    openingHours: '周二至周日 9:00-17:00',
  },
  {
    id: 'chengdu-museum',
    name: 'Chengdu Museum',
    nameLocal: '成都市博物馆',
    description: '展示成都历史文化的大型综合性博物馆。',
    lat: 30.5714,
    lng: 104.0665,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Chengdu',
    foundedYear: 1958,
    popularity: 80,
    annualVisitors: 900000,
    highlights: ['皮影戏', '蜀绣', '三星堆文物复制'],
    openingHours: '周二至周日 9:00-17:00',
    website: 'https://www.cdmuseum.com',
  },
  {
    id: 'chongqing-museum',
    name: 'Chongqing Museum',
    nameLocal: '重庆中国三峡博物馆',
    description: '展示三峡历史和文化的重要博物馆。',
    lat: 29.5630,
    lng: 106.5514,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Chongqing',
    foundedYear: 1949,
    popularity: 82,
    annualVisitors: 1000000,
    highlights: ['三峡文物', '抗战文物', '巴蜀文化'],
    openingHours: '周二至周日 9:00-17:00',
    website: 'https://www.3xmuseum.cn',
  },
  {
    id: 'tianjin-museum',
    name: 'Tianjin Museum',
    nameLocal: '天津博物馆',
    description: '天津市最大的综合性博物馆。',
    lat: 39.1256,
    lng: 117.1909,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Tianjin',
    foundedYear: 1918,
    popularity: 81,
    annualVisitors: 900000,
    highlights: ['天津历史陈列', '津门故里', '民间艺术'],
    openingHours: '周二至周日 9:00-16:30',
    website: 'https://www.tjbwg.com',
  },
  {
    id: 'hebei-museum',
    name: 'Hebei Museum',
    nameLocal: '河北省博物馆',
    description: '展示燕赵文化的重要博物馆。',
    lat: 38.0042,
    lng: 114.5149,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Shijiazhuang',
    foundedYear: 1953,
    popularity: 79,
    annualVisitors: 800000,
    highlights: ['中山国文物', '燕赵青铜器', '河北民俗'],
    openingHours: '周二至周日 9:00-17:00',
    website: 'https://www.hebeimuseum.org.cn',
  },
  {
    id: ' Shanxi Museum',
    name: 'Shanxi Museum',
    nameLocal: '山西省博物院',
    description: '中国地方综合性博物馆之一。',
    lat: 37.8706,
    lng: 112.5487,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Taiyuan',
    foundedYear: 1919,
    popularity: 83,
    annualVisitors: 1000000,
    highlights: ['晋国文物', '壁画', '佛教艺术'],
    openingHours: '周二至周日 9:00-17:00',
    website: 'https://www.shanximuseum.com',
  },
  {
    id: 'gansu-museum',
    name: 'Gansu Provincial Museum',
    nameLocal: '甘肃省博物馆',
    description: '展示丝绸之路文化的重要博物馆。',
    lat: 36.0602,
    lng: 103.8341,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Lanzhou',
    foundedYear: 1939,
    popularity: 80,
    annualVisitors: 850000,
    highlights: ['马踏飞燕', '甘肃彩陶', '丝绸之路文物'],
    openingHours: '周二至周日 9:00-17:00',
    website: 'https://www.gansumuseum.com',
  },
  {
    id: 'xinjiang-museum',
    name: 'Xinjiang Uygur Autonomous Region Museum',
    nameLocal: '新疆维吾尔自治区博物馆',
    description: '展示西域文化的重要博物馆。',
    lat: 43.8256,
    lng: 87.6168,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Urumqi',
    foundedYear: 1959,
    popularity: 79,
    annualVisitors: 800000,
    highlights: ['新疆古代干尸', '丝路文物', '民族服饰'],
    openingHours: '周二至周日 10:00-18:00',
    website: 'https://www.xjmuseum.com.cn',
  },
  {
    id: 'inner-mongolia-museum',
    name: 'Inner Mongolia Museum',
    nameLocal: '内蒙古博物院',
    description: '展示草原文化的重要博物馆。',
    lat: 40.8424,
    lng: 111.7492,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Hohhot',
    foundedYear: 1957,
    popularity: 78,
    annualVisitors: 750000,
    highlights: ['蒙古族文物', '草原青铜器', '恐龙化石'],
    openingHours: '周二至周日 9:00-17:00',
    website: 'https://www.nmgbwy.com',
  },
  {
    id: 'guizhou-museum',
    name: 'Guizhou Museum',
    nameLocal: '贵州省博物馆',
    description: '展示贵州多元民族文化的博物馆。',
    lat: 26.5982,
    lng: 106.7073,
    type: 'cultural',
    continent: 'Asia',
    country: 'China',
    city: 'Guiyang',
    foundedYear: 1953,
    popularity: 76,
    annualVisitors: 600000,
    highlights: ['少数民族服饰', '苗族银饰', '贵州古生物'],
    openingHours: '周二至周日 9:00-17:00',
    website: 'https://www.gzmusuem.cn',
  },
  {
    id: 'guanxi-museum',
    name: 'Guangxi Museum',
    nameLocal: '广西民族博物馆',
    description: '展示广西民族文化的专题博物馆。',
    lat: 22.8173,
    lng: 108.4014,
    type: 'cultural',
    continent: 'Asia',
    country: 'China',
    city: 'Nanning',
    foundedYear: 1988,
    popularity: 77,
    annualVisitors: 650000,
    highlights: ['壮族文物', '铜鼓文化', '民族建筑'],
    openingHours: '周二至周日 9:00-17:00',
    website: 'https://www.gxmuseum.com.cn',
  },
  {
    id: 'haikou-museum',
    name: 'Hainan Museum',
    nameLocal: '海南省博物馆',
    description: '展示海南历史文化的大型博物馆。',
    lat: 20.0443,
    lng: 110.3491,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Haikou',
    foundedYear: 2008,
    popularity: 74,
    annualVisitors: 500000,
    highlights: ['海南历史陈列', '海上丝绸之路', '黎族文化'],
    openingHours: '周二至周日 9:00-17:00',
    website: 'https://www.hainanmuseum.com',
  },
  {
    id: 'ningxia-museum',
    name: 'Ningxia Museum',
    nameLocal: '宁夏回族自治区博物馆',
    description: '展示西夏文化和回族风情的博物馆。',
    lat: 38.4872,
    lng: 106.2315,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Yinchuan',
    foundedYear: 1973,
    popularity: 76,
    annualVisitors: 550000,
    highlights: ['西夏文物', '贺兰山岩画', '回族民俗'],
    openingHours: '周二至周日 9:00-17:00',
    website: 'https://www.nxmg.gov.cn',
  },
  {
    id: 'qinghai-museum',
    name: 'Qinghai Museum',
    nameLocal: '青海省博物馆',
    description: '展示青海历史民族文化的重要窗口。',
    lat: 36.6171,
    lng: 101.7782,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Xining',
    foundedYear: 1986,
    popularity: 75,
    annualVisitors: 500000,
    highlights: ['青海彩陶', '唐蕃古道文物', '藏族文化'],
    openingHours: '周二至周日 9:00-17:00',
    website: 'https://www.qhmuseum.cn',
  },
  {
    id: 'tibet-museum',
    name: 'Tibet Museum',
    nameLocal: '西藏博物馆',
    description: '展示西藏历史文化的重要博物馆。',
    lat: 29.6525,
    lng: 91.1171,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Lhasa',
    foundedYear: 1999,
    popularity: 82,
    annualVisitors: 800000,
    highlights: ['藏传佛教文物', '吐蕃文物', '藏族民俗'],
    openingHours: '周二至周日 10:00-17:30',
    website: 'https://www.tibetmuseum.cn',
  },
  {
    id: 'jilin-museum',
    name: 'Jilin Museum',
    nameLocal: '吉林省博物院',
    description: '展示吉林历史文化的重要博物馆。',
    lat: 43.8968,
    lng: 125.3245,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Changchun',
    foundedYear: 1951,
    popularity: 77,
    annualVisitors: 600000,
    highlights: ['东北抗联文物', '满族文物', '稀土资源'],
    openingHours: '周二至周日 9:00-16:30',
    website: 'https://www.jlmuseum.cn',
  },
  {
    id: 'heilongjiang-museum',
    name: 'Heilongjiang Museum',
    nameLocal: '黑龙江省博物馆',
    description: '展示黑龙江历史文化的重要窗口。',
    lat: 45.7520,
    lng: 126.6421,
    type: 'history',
    continent: 'Asia',
    country: 'China',
    city: 'Harbin',
    foundedYear: 1923,
    popularity: 78,
    annualVisitors: 650000,
    highlights: ['黑龙江流域文明', '东北原始文化', '冰雪文化'],
    openingHours: '周二至周日 9:00-16:00',
    website: 'https://www.hljmuseum.com',
  },
  {
    id: 'singapore-national-museum',
    name: 'National Museum of Singapore',
    nameLocal: '新加坡国家博物馆',
    description: '新加坡最古老的博物馆，讲述新加坡700年的历史。',
    lat: 1.2967,
    lng: 103.8486,
    type: 'history',
    continent: 'Asia',
    country: 'Singapore',
    city: 'Singapore',
    foundedYear: 1887,
    popularity: 78,
    annualVisitors: 900000,
    highlights: ['新加坡历史画廊', '生活画廊', '新加坡石'],
    openingHours: '每日 10:00-19:00',
    website: 'https://www.nhb.gov.sg/nationalmuseum',
  },
  {
    id: 'islamic-art-doha',
    name: 'Museum of Islamic Art',
    nameLocal: '伊斯兰艺术博物馆',
    description: '世界上最完整的伊斯兰艺术收藏之一，建筑由贝聿铭设计。',
    lat: 25.2959,
    lng: 51.5395,
    type: 'art',
    continent: 'Asia',
    country: 'Qatar',
    city: 'Doha',
    foundedYear: 2008,
    popularity: 84,
    annualVisitors: 800000,
    highlights: ['波斯地毯', '玻璃器皿', '金属工艺', '伊斯兰书法'],
    openingHours: '周六至周四 9:00-19:00；周五 13:30-19:00',
    website: 'https://mia.org.qa',
  },
  
  // North America
  {
    id: 'met',
    name: 'The Metropolitan Museum of Art',
    nameLocal: '大都会艺术博物馆',
    description: '美国最大的艺术博物馆，藏品跨越5000年人类文明史。',
    lat: 40.7794,
    lng: -73.9632,
    type: 'art',
    continent: 'North America',
    country: 'United States',
    city: 'New York',
    foundedYear: 1870,
    popularity: 98,
    annualVisitors: 6479000,
    highlights: ['埃及神庙', '欧洲绘画', '美国艺术翼', '武器盔甲'],
    openingHours: '周日至周四 10:00-17:00；周五、周六 10:00-21:00',
    website: 'https://www.metmuseum.org',
  },
  {
    id: 'smithsonian-natural-history',
    name: 'Smithsonian National Museum of Natural History',
    nameLocal: '史密森尼自然历史博物馆',
    description: '世界上参观人数最多的自然历史博物馆，收藏1.45亿件标本。',
    lat: 38.8913,
    lng: -77.0261,
    type: 'natural-history',
    continent: 'North America',
    country: 'United States',
    city: 'Washington D.C.',
    foundedYear: 1910,
    popularity: 96,
    annualVisitors: 7100000,
    highlights: ['希望钻石', '恐龙化石', '人类起源展', '海洋大厅'],
    openingHours: '每日 10:00-17:30',
    website: 'https://naturalhistory.si.edu',
  },
  {
    id: 'moma',
    name: 'Museum of Modern Art',
    nameLocal: '现代艺术博物馆',
    description: '世界上最重要的现代艺术博物馆之一，定义了现代艺术的收藏标准。',
    lat: 40.7614,
    lng: -73.9776,
    type: 'art',
    continent: 'North America',
    country: 'United States',
    city: 'New York',
    foundedYear: 1929,
    popularity: 94,
    annualVisitors: 2800000,
    highlights: ['梵高的星夜', '毕加索的亚威农少女', '沃霍尔的金宝汤罐头'],
    openingHours: '每日 10:30-17:30；周六至19:00',
    website: 'https://www.moma.org',
  },
  {
    id: 'national-gallery-art',
    name: 'National Gallery of Art',
    nameLocal: '美国国家美术馆',
    description: '收藏欧洲和美国艺术杰作的世界级美术馆。',
    lat: 38.8913,
    lng: -77.0198,
    type: 'art',
    continent: 'North America',
    country: 'United States',
    city: 'Washington D.C.',
    foundedYear: 1937,
    popularity: 92,
    annualVisitors: 4400000,
    highlights: ['达芬奇的吉内薇拉·德·本奇', '莫奈的��莲', '雕塑花园'],
    openingHours: '周一至周六 10:00-17:00；周日 11:00-18:00',
    website: 'https://www.nga.gov',
  },
  {
    id: 'chicago-art-institute',
    name: 'Art Institute of Chicago',
    nameLocal: '芝加哥艺术博物馆',
    description: '美国第二大艺术博物馆，以印象派收藏闻名。',
    lat: 41.8796,
    lng: -87.6237,
    type: 'art',
    continent: 'North America',
    country: 'United States',
    city: 'Chicago',
    foundedYear: 1879,
    popularity: 91,
    annualVisitors: 1700000,
    highlights: ['修拉的大碗岛星期日下午', '格兰特·伍德的美国哥特式', '莫奈收藏'],
    openingHours: '每日 11:00-17:00；周四至20:00',
    website: 'https://www.artic.edu',
  },
  {
    id: 'lacma',
    name: 'Los Angeles County Museum of Art',
    nameLocal: '洛杉矶县艺术博物馆',
    description: '美国西部最大的艺术博物馆，收藏跨越6000年。',
    lat: 34.0639,
    lng: -118.3592,
    type: 'art',
    continent: 'North America',
    country: 'United States',
    city: 'Los Angeles',
    foundedYear: 1961,
    popularity: 85,
    annualVisitors: 1600000,
    highlights: ['城市之光', '亚洲艺术馆', '拉丁美洲艺术', '现代艺术'],
    openingHours: '周一、周二、周四 11:00-18:00；周五 11:00-20:00；周六、周日 10:00-19:00',
    website: 'https://www.lacma.org',
  },
  {
    id: 'royal-ontario-museum',
    name: 'Royal Ontario Museum',
    nameLocal: '皇家安大略博物馆',
    description: '加拿大最大的博物馆，涵盖自然历史和世界文化。',
    lat: 43.6677,
    lng: -79.3948,
    type: 'natural-history',
    continent: 'North America',
    country: 'Canada',
    city: 'Toronto',
    foundedYear: 1912,
    popularity: 83,
    annualVisitors: 1350000,
    highlights: ['恐龙展厅', '中国艺术', '宝石矿物', '古代埃及'],
    openingHours: '每日 10:00-17:30',
    website: 'https://www.rom.on.ca',
  },
  {
    id: 'anthropology-mexico',
    name: 'National Museum of Anthropology',
    nameLocal: '墨西哥国家人类学博物馆',
    description: '拉丁美洲最大的博物馆，展示墨西哥前哥伦布时期文明。',
    lat: 19.4260,
    lng: -99.1861,
    type: 'archaeology',
    continent: 'North America',
    country: 'Mexico',
    city: 'Mexico City',
    foundedYear: 1964,
    popularity: 90,
    annualVisitors: 2300000,
    highlights: ['阿兹特克太阳石', '玛雅展厅', '奥尔梅克巨石头像'],
    openingHours: '周二至周日 9:00-19:00',
    website: 'https://www.mna.inah.gob.mx',
  },
  {
    id: 'air-space-dc',
    name: 'National Air and Space Museum',
    nameLocal: '国家航空航天博物馆',
    description: '世界上收藏航空航天器最多的博物馆。',
    lat: 38.8882,
    lng: -77.0199,
    type: 'technology',
    continent: 'North America',
    country: 'United States',
    city: 'Washington D.C.',
    foundedYear: 1946,
    popularity: 95,
    annualVisitors: 6200000,
    highlights: ['莱特兄弟飞机', '阿波罗11号指挥舱', '圣路易斯精神号'],
    openingHours: '每日 10:00-17:30',
    website: 'https://airandspace.si.edu',
  },
  
  // South America
  {
    id: 'museo-nacional-brazil',
    name: 'Museu Nacional',
    nameLocal: '巴西国家博物馆',
    description: '巴西最古老的科学机构，拥有超过2000万件藏品（2018年火灾后重建中）。',
    lat: -22.9056,
    lng: -43.2258,
    type: 'natural-history',
    continent: 'South America',
    country: 'Brazil',
    city: 'Rio de Janeiro',
    foundedYear: 1818,
    popularity: 75,
    annualVisitors: 500000,
    highlights: ['恐龙化石', '埃及木乃伊', '原住民文化', '陨石收藏'],
    openingHours: '周二至周日 10:00-17:00',
    website: 'https://www.museunacional.ufrj.br',
  },
  {
    id: 'masp',
    name: 'Museu de Arte de São Paulo',
    nameLocal: '圣保罗艺术博物馆',
    description: '拉丁美洲最重要的艺术博物馆，以独特的玻璃展示架闻名。',
    lat: -23.5614,
    lng: -46.6560,
    type: 'art',
    continent: 'South America',
    country: 'Brazil',
    city: 'São Paulo',
    foundedYear: 1947,
    popularity: 84,
    annualVisitors: 700000,
    highlights: ['拉斐尔作品', '伦勃朗作品', '印象派收藏', '巴西现代艺术'],
    openingHours: '周二至周日 10:00-18:00；周四至20:00',
    website: 'https://masp.org.br',
  },
  {
    id: 'larco-museum',
    name: 'Museo Larco',
    nameLocal: '拉尔科博物馆',
    description: '收藏秘鲁前哥伦布时期艺术的私人博物馆，藏品精美。',
    lat: -12.0727,
    lng: -77.0707,
    type: 'archaeology',
    continent: 'South America',
    country: 'Peru',
    city: 'Lima',
    foundedYear: 1926,
    popularity: 79,
    annualVisitors: 400000,
    highlights: ['莫切陶器', '黄金饰品', '纺织品', '情色艺术收藏'],
    openingHours: '每日 9:00-22:00',
    website: 'https://www.museolarco.org',
  },
  {
    id: 'museo-nacional-colombia',
    name: 'Museo Nacional de Colombia',
    nameLocal: '哥伦比亚国家博物馆',
    description: '哥伦比亚最古老的博物馆，展示该国丰富的历史和艺术。',
    lat: 4.6147,
    lng: -74.0687,
    type: 'history',
    continent: 'South America',
    country: 'Colombia',
    city: 'Bogotá',
    foundedYear: 1823,
    popularity: 76,
    annualVisitors: 350000,
    highlights: ['前哥伦布时期艺术', '殖民时期艺术', '独立战争文物'],
    openingHours: '周二至周六 10:00-18:00；周日 10:00-17:00',
    website: 'https://www.museonacional.gov.co',
  },
  {
    id: 'gold-museum-bogota',
    name: 'Museo del Oro',
    nameLocal: '黄金博物馆',
    description: '世界上最大的前哥伦布时期黄金艺术品收藏。',
    lat: 4.6018,
    lng: -74.0722,
    type: 'archaeology',
    continent: 'South America',
    country: 'Colombia',
    city: 'Bogotá',
    foundedYear: 1939,
    popularity: 82,
    annualVisitors: 500000,
    highlights: ['穆伊斯卡黄金筏', '黄金面具', '宝石装饰品'],
    openingHours: '周二至周六 9:00-18:00；周日 10:00-16:00',
    website: 'https://www.banrepcultural.org/bogota/museo-del-oro',
  },
  
  // Africa
  {
    id: 'egyptian-museum-cairo',
    name: 'Egyptian Museum',
    nameLocal: '开罗埃及博物馆',
    description: '世界上最重要的埃及文物收藏，包括图坦卡蒙珍宝。',
    lat: 30.0478,
    lng: 31.2336,
    type: 'archaeology',
    continent: 'Africa',
    country: 'Egypt',
    city: 'Cairo',
    foundedYear: 1902,
    popularity: 93,
    annualVisitors: 2500000,
    highlights: ['图坦卡蒙黄金面具', '木乃伊室', '皇家珠宝', '阿肯那顿时期'],
    openingHours: '每日 9:00-17:00',
    website: 'https://www.egyptianmuseum.org',
  },
  {
    id: 'grand-egyptian-museum',
    name: 'Grand Egyptian Museum',
    nameLocal: '大埃及博物馆',
    description: '世界上最大的考古博物馆，专门展示古埃及文明。',
    lat: 29.9956,
    lng: 31.1287,
    type: 'archaeology',
    continent: 'Africa',
    country: 'Egypt',
    city: 'Giza',
    foundedYear: 2024,
    popularity: 88,
    annualVisitors: 1500000,
    highlights: ['图坦卡蒙完整收藏', '胡夫太阳船', '金字塔景观'],
    openingHours: '每日 9:00-18:00',
    website: 'https://grandegyptianmuseum.org',
  },
  {
    id: 'apartheid-museum',
    name: 'Apartheid Museum',
    nameLocal: '种族隔离博物馆',
    description: '记录南非种族隔离历史的重要博物馆。',
    lat: -26.2375,
    lng: 28.0103,
    type: 'history',
    continent: 'Africa',
    country: 'South Africa',
    city: 'Johannesburg',
    foundedYear: 2001,
    popularity: 80,
    annualVisitors: 300000,
    highlights: ['曼德拉展区', '历史照片', '互动展览'],
    openingHours: '每日 9:00-17:00',
    website: 'https://www.apartheidmuseum.org',
  },
  {
    id: 'zeitz-mocaa',
    name: 'Zeitz MOCAA',
    nameLocal: '蔡茨非洲当代艺术博物馆',
    description: '非洲最大的当代艺术博物馆，位于改造的谷仓建筑中。',
    lat: -33.9082,
    lng: 18.4173,
    type: 'art',
    continent: 'Africa',
    country: 'South Africa',
    city: 'Cape Town',
    foundedYear: 2017,
    popularity: 77,
    annualVisitors: 200000,
    highlights: ['非洲当代艺术', '建筑本身', '摄影收藏'],
    openingHours: '周三至周一 10:00-18:00',
    website: 'https://zeitzmocaa.museum',
  },
  {
    id: 'nairobi-national-museum',
    name: 'Nairobi National Museum',
    nameLocal: '内罗毕国家博物馆',
    description: '肯尼亚最大的博物馆，展示东非自然和文化遗产。',
    lat: -1.2741,
    lng: 36.8144,
    type: 'natural-history',
    continent: 'Africa',
    country: 'Kenya',
    city: 'Nairobi',
    foundedYear: 1910,
    popularity: 74,
    annualVisitors: 250000,
    highlights: ['人类起源展', '野生动物标本', '肯尼亚艺术'],
    openingHours: '每日 8:30-17:30',
    website: 'https://museums.or.ke',
  },
  
  // Oceania
  {
    id: 'australian-museum',
    name: 'Australian Museum',
    nameLocal: '澳大利亚博物馆',
    description: '澳大利亚最古老的博物馆，专注于自然历史和原住民文化。',
    lat: -33.8743,
    lng: 151.2131,
    type: 'natural-history',
    continent: 'Oceania',
    country: 'Australia',
    city: 'Sydney',
    foundedYear: 1827,
    popularity: 81,
    annualVisitors: 850000,
    highlights: ['恐龙展', '原住民艺术', '太平洋文化', '澳大利亚野生动物'],
    openingHours: '每日 10:00-17:00',
    website: 'https://australian.museum',
  },
  {
    id: 'te-papa',
    name: 'Museum of New Zealand Te Papa Tongarewa',
    nameLocal: '新西兰国家博物馆',
    description: '新西兰最大的博物馆，以创新的互动展览闻名。',
    lat: -41.2904,
    lng: 174.7820,
    type: 'cultural',
    continent: 'Oceania',
    country: 'New Zealand',
    city: 'Wellington',
    foundedYear: 1998,
    popularity: 85,
    annualVisitors: 1500000,
    highlights: ['毛利文化', '大鱿鱼标本', '地震体验', '新西兰艺术'],
    openingHours: '每日 10:00-18:00',
    website: 'https://www.tepapa.govt.nz',
  },
  {
    id: 'ngv',
    name: 'National Gallery of Victoria',
    nameLocal: '维多利亚国家美术馆',
    description: '澳大利亚历史最悠久、规模最大的美术馆。',
    lat: -37.8226,
    lng: 144.9689,
    type: 'art',
    continent: 'Oceania',
    country: 'Australia',
    city: 'Melbourne',
    foundedYear: 1861,
    popularity: 83,
    annualVisitors: 2800000,
    highlights: ['欧洲艺术', '亚洲艺术', '澳大利亚艺术', '当代设计'],
    openingHours: '每日 10:00-17:00',
    website: 'https://www.ngv.vic.gov.au',
  },
  {
    id: 'queensland-museum',
    name: 'Queensland Museum',
    nameLocal: '昆士兰博物馆',
    description: '展示昆士兰自然和文化遗产的综合性博物馆。',
    lat: -27.4713,
    lng: 153.0156,
    type: 'natural-history',
    continent: 'Oceania',
    country: 'Australia',
    city: 'Brisbane',
    foundedYear: 1862,
    popularity: 76,
    annualVisitors: 700000,
    highlights: ['恐龙花园', '大堡礁展', '原住民文化', '昆士兰历史'],
    openingHours: '每日 9:30-17:00',
    website: 'https://www.qm.qld.gov.au',
  },
  
  // Additional European Museums
  {
    id: 'pergamon',
    name: 'Pergamon Museum',
    nameLocal: '佩加蒙博物馆',
    description: '柏林最受欢迎的博物馆，收藏古代建筑重建。',
    lat: 52.5211,
    lng: 13.3969,
    type: 'archaeology',
    continent: 'Europe',
    country: 'Germany',
    city: 'Berlin',
    foundedYear: 1930,
    popularity: 89,
    annualVisitors: 1100000,
    highlights: ['佩加蒙祭坛', '伊什塔尔门', '米利都市场门'],
    openingHours: '周二至周日 10:00-18:00；周四至20:00',
    website: 'https://www.smb.museum',
  },
  {
    id: 'orsay',
    name: "Musée d'Orsay",
    nameLocal: '奥赛博物馆',
    description: '世界上最大的印象派艺术收藏，位于前火车站建筑内。',
    lat: 48.8600,
    lng: 2.3266,
    type: 'art',
    continent: 'Europe',
    country: 'France',
    city: 'Paris',
    foundedYear: 1986,
    popularity: 93,
    annualVisitors: 3300000,
    highlights: ['梵高的自画像', '莫奈的睡莲', '雷诺阿的煎饼磨坊舞会'],
    openingHours: '周二至周日 9:30-18:00；周四至21:45',
    website: 'https://www.musee-orsay.fr',
  },
  {
    id: 'kunsthistorisches',
    name: 'Kunsthistorisches Museum',
    nameLocal: '艺术史博物馆',
    description: '维也纳最大的美术馆，收藏哈布斯堡王朝艺术珍品。',
    lat: 48.2038,
    lng: 16.3616,
    type: 'art',
    continent: 'Europe',
    country: 'Austria',
    city: 'Vienna',
    foundedYear: 1891,
    popularity: 86,
    annualVisitors: 1400000,
    highlights: ['勃鲁盖尔收藏', '拉斐尔作品', '埃及和近东收藏'],
    openingHours: '周二至周日 10:00-18:00；周四至21:00',
    website: 'https://www.khm.at',
  },
  {
    id: 'vasa-museum',
    name: 'Vasa Museum',
    nameLocal: '瓦萨博物馆',
    description: '展示17世纪瓦萨号战舰的专题博物馆，是斯堪的纳维亚最受欢迎的博物馆。',
    lat: 59.3280,
    lng: 18.0914,
    type: 'maritime',
    continent: 'Europe',
    country: 'Sweden',
    city: 'Stockholm',
    foundedYear: 1990,
    popularity: 87,
    annualVisitors: 1300000,
    highlights: ['瓦萨号战舰', '船员生活展', '打捞历史'],
    openingHours: '每日 10:00-17:00；周三至20:00',
    website: 'https://www.vasamuseet.se',
  },
  {
    id: 'topkapi',
    name: 'Topkapi Palace Museum',
    nameLocal: '托普卡帕宫博物馆',
    description: '奥斯曼帝国苏丹的宫殿，展示帝国珍宝和伊斯兰文物。',
    lat: 41.0115,
    lng: 28.9833,
    type: 'history',
    continent: 'Europe',
    country: 'Turkey',
    city: 'Istanbul',
    foundedYear: 1924,
    popularity: 88,
    annualVisitors: 2000000,
    highlights: ['托普卡帕匕首', '先知遗物', '后宫', '帝国珍宝'],
    openingHours: '周三至周一 9:00-19:00',
    website: 'https://www.millisaraylar.gov.tr',
  },
  
  // Additional Asian Museums
  {
    id: 'national-palace-taipei',
    name: 'National Palace Museum',
    nameLocal: '台北故宫博物院',
    description: '收藏中国皇家艺术品的世界级博物馆，藏品近70万件。',
    lat: 25.1024,
    lng: 121.5485,
    type: 'art',
    continent: 'Asia',
    country: 'Taiwan',
    city: 'Taipei',
    foundedYear: 1965,
    popularity: 91,
    annualVisitors: 4500000,
    highlights: ['翠玉白菜', '肉形石', '毛公鼎', '富春山居图'],
    openingHours: '每日 8:30-18:30；周五、周六至21:00',
    website: 'https://www.npm.gov.tw',
  },
  {
    id: 'hong-kong-museum-art',
    name: 'Hong Kong Museum of Art',
    nameLocal: '香港艺术馆',
    description: '香港最大的公共艺术博物馆，收藏中国艺术和本地作品。',
    lat: 22.2936,
    lng: 114.1717,
    type: 'art',
    continent: 'Asia',
    country: 'Hong Kong',
    city: 'Hong Kong',
    foundedYear: 1962,
    popularity: 78,
    annualVisitors: 600000,
    highlights: ['中国书画', '至乐楼藏品', '香港艺术', '国际展览'],
    openingHours: '周一至周三、周五 10:00-18:00；周六、周日 10:00-19:00',
    website: 'https://hk.art.museum',
  },
  {
    id: 'mori-art-museum',
    name: 'Mori Art Museum',
    nameLocal: '森美术馆',
    description: '位于六本木新城的当代艺术博物馆，可俯瞰东京全景。',
    lat: 35.6604,
    lng: 139.7292,
    type: 'art',
    continent: 'Asia',
    country: 'Japan',
    city: 'Tokyo',
    foundedYear: 2003,
    popularity: 81,
    annualVisitors: 1500000,
    highlights: ['当代艺术展', '东京城市观景台', '国际艺术家作品'],
    openingHours: '每日 10:00-22:00；周二至17:00',
    website: 'https://www.mori.art.museum',
  },
  {
    id: 'vietnam-ethnology',
    name: 'Vietnam Museum of Ethnology',
    nameLocal: '越南民族学博物���',
    description: '展示越南54个民族文化的综合博物馆。',
    lat: 21.0401,
    lng: 105.7981,
    type: 'cultural',
    continent: 'Asia',
    country: 'Vietnam',
    city: 'Hanoi',
    foundedYear: 1997,
    popularity: 77,
    annualVisitors: 400000,
    highlights: ['少数民族服饰', '传统建筑', '日常生活展', '宗教文物'],
    openingHours: '周二至周日 8:30-17:30',
    website: 'http://www.vme.org.vn',
  },
  {
    id: 'thai-national-museum',
    name: 'National Museum Bangkok',
    nameLocal: '曼谷国家博物馆',
    description: '东南亚最大的博物馆，收藏泰国艺术和历史文物。',
    lat: 13.7578,
    lng: 100.4914,
    type: 'history',
    continent: 'Asia',
    country: 'Thailand',
    city: 'Bangkok',
    foundedYear: 1874,
    popularity: 79,
    annualVisitors: 350000,
    highlights: ['素可泰艺术', '皇家车辇', '佛教艺术', '泰国历史'],
    openingHours: '周三至周日 9:00-16:00',
    website: 'https://www.nationalmuseums.go.th',
  },

  // 更多欧洲博物馆
  {
    id: 'albertina',
    name: 'Albertina',
    nameLocal: '阿尔贝蒂娜博物馆',
    description: '维也纳最重要的艺术博物馆之一，收藏超过100万件艺术品。',
    lat: 48.1941,
    lng: 16.3693,
    type: 'art',
    continent: 'Europe',
    country: 'Austria',
    city: 'Vienna',
    foundedYear: 1768,
    popularity: 82,
    annualVisitors: 900000,
    highlights: ['丢勒作品', '莫奈作品', '毕加索作品', '古典大师素描'],
    openingHours: '周三至周一 10:00-18:00；周五 10:00-21:00',
    website: 'https://www.albertina.at',
  },
  {
    id: 'van-gogh-museum',
    name: 'Van Gogh Museum',
    nameLocal: '梵高博物馆',
    description: '世界上收藏梵高作品最多的博物馆。',
    lat: 52.3584,
    lng: 4.8811,
    type: 'art',
    continent: 'Europe',
    country: 'Netherlands',
    city: 'Amsterdam',
    foundedYear: 1973,
    popularity: 91,
    annualVisitors: 2100000,
    highlights: ['星空', '向日葵', '自画像', '卧室'],
    openingHours: '每日 9:00-18:00',
    website: 'https://www.vangoghmuseum.nl',
  },
  {
    id: 'casa-batllo',
    name: 'Casa Batlló',
    nameLocal: '巴特罗之家',
    description: '巴塞罗那的现代主义建筑杰作，由高迪设计。',
    lat: 41.3916,
    lng: 2.1750,
    type: 'cultural',
    continent: 'Europe',
    country: 'Spain',
    city: 'Barcelona',
    foundedYear: 1877,
    popularity: 88,
    annualVisitors: 1000000,
    highlights: ['龙脊屋顶', '彩色玻璃', '骨骼支柱', '外立面'],
    openingHours: '每日 9:00-21:00',
    website: 'https://www.casabatllo.es',
  },
  {
    id: 'ulm-museum',
    name: 'Ulmer Museum',
    nameLocal: '乌尔姆博物馆',
    description: '德国重要的文化和艺术博物馆。',
    lat: 48.3984,
    lng: 9.9915,
    type: 'art',
    continent: 'Europe',
    country: 'Germany',
    city: 'Ulm',
    foundedYear: 1841,
    popularity: 75,
    annualVisitors: 200000,
    highlights: ['中世纪艺术', '现代艺术', '考古展'],
    openingHours: '周二至周日 11:00-17:00',
    website: 'https://www.ulmer-museum.de',
  },
  {
    id: 'milan-cathedral-museum',
    name: 'Duomo Museum Milan',
    nameLocal: '米兰大教堂博物馆',
    description: '展示米兰大教堂的艺术珍品和历史文物。',
    lat: 45.4642,
    lng: 9.1900,
    type: 'art',
    continent: 'Europe',
    country: 'Italy',
    city: 'Milan',
    foundedYear: 1868,
    popularity: 80,
    annualVisitors: 500000,
    highlights: ['大教堂模型', '彩色玻璃', '圣像'],
    openingHours: '每日 10:00-18:00',
    website: 'https://www.duomomilano.it',
  },
  {
    id: 'burgerbibliothek',
    name: 'Burgerbibliothek',
    nameLocal: '伯尔尼图书馆',
    description: '瑞士伯尔尼的历史文献和手稿图书馆。',
    lat: 46.9480,
    lng: 7.4474,
    type: 'history',
    continent: 'Europe',
    country: 'Switzerland',
    city: 'Bern',
    foundedYear: 1954,
    popularity: 72,
    annualVisitors: 150000,
    highlights: ['中世纪手稿', '历史文献', '地图收藏'],
    openingHours: '周一至周五 9:00-18:00',
    website: 'https://www.burgerbibliothek.ch',
  },
  {
    id: 'prague-jewish-museum',
    name: 'Jewish Museum Prague',
    nameLocal: '布拉格犹太博物馆',
    description: '世界上最重要的犹太历史博物馆之一。',
    lat: 50.0902,
    lng: 14.4180,
    type: 'history',
    continent: 'Europe',
    country: 'Czech Republic',
    city: 'Prague',
    foundedYear: 1906,
    popularity: 85,
    annualVisitors: 700000,
    highlights: ['老新犹太教堂', '犹太公墓', '弗朗茨·卡夫卡展'],
    openingHours: '每日 9:00-18:00',
    website: 'https://www.jewishmuseum.cz',
  },
  {
    id: 'madrid-royal-academy',
    name: 'Royal Academy of Fine Arts',
    nameLocal: '马德里皇家美术学院',
    description: '西班牙重要的艺术学院和博物馆。',
    lat: 40.4183,
    lng: -3.6995,
    type: 'art',
    continent: 'Europe',
    country: 'Spain',
    city: 'Madrid',
    foundedYear: 1752,
    popularity: 78,
    annualVisitors: 400000,
    highlights: ['戈雅作品', '西班牙宫廷画', '西班牙艺术史'],
    openingHours: '周二至周日 10:00-15:00',
    website: 'https://www.rafmadrid.org',
  },
  {
    id: 'budapest-museum',
    name: 'Museum of Fine Arts',
    nameLocal: '布达佩斯美术博物馆',
    description: '匈牙利最大的艺术博物馆。',
    lat: 47.5015,
    lng: 19.0549,
    type: 'art',
    continent: 'Europe',
    country: 'Hungary',
    city: 'Budapest',
    foundedYear: 1900,
    popularity: 80,
    annualVisitors: 500000,
    highlights: ['埃及艺术', '欧洲绘画', '古代雕塑'],
    openingHours: '周二至周日 10:00-18:00',
    website: 'https://www.mfab.hu',
  },
  {
    id: 'lisbon-museum',
    name: 'Museu Nacional de Arte Antiga',
    nameLocal: '里斯本古代艺术博物馆',
    description: '葡萄牙最重要的艺术博物馆。',
    lat: 38.7098,
    lng: -9.1456,
    type: 'art',
    continent: 'Europe',
    country: 'Portugal',
    city: 'Lisbon',
    foundedYear: 1884,
    popularity: 79,
    annualVisitors: 400000,
    highlights: ['圣文生祭坛画', '葡萄牙瓷砖', '镀金木雕'],
    openingHours: '周二至周日 10:00-18:00',
    website: 'https://www.museularteantiga.pt',
  },
  {
    id: 'copenhagen-museum',
    name: 'National Museum of Denmark',
    nameLocal: '丹麦国家博物馆',
    description: '丹麦最大的文化历史博物馆。',
    lat: 55.5694,
    lng: 12.5688,
    type: 'history',
    continent: 'Europe',
    country: 'Denmark',
    city: 'Copenhagen',
    foundedYear: 1807,
    popularity: 83,
    annualVisitors: 800000,
    highlights: ['维京文物', '格陵兰文物', '丹麦史前史'],
    openingHours: '每日 10:00-17:00',
    website: 'https://www.natmus.dk',
  },
  {
    id: 'oslo-museum',
    name: 'National Museum Norway',
    nameLocal: '挪威国家博物馆',
    description: '挪威最大的艺术和文化博物馆。',
    lat: 59.9139,
    lng: 10.7522,
    type: 'art',
    continent: 'Europe',
    country: 'Norway',
    city: 'Oslo',
    foundedYear: 2003,
    popularity: 84,
    annualVisitors: 900000,
    highlights: ['呐喊', '蒙克作品', '挪威现代艺术'],
    openingHours: '每日 10:00-18:00；周五至20:00',
    website: 'https://www.nationalmuseum.no',
  },
  {
    id: 'helsinki-museum',
    name: 'Ateneum Art Museum',
    nameLocal: 'Ateneum艺术博物馆',
    description: '芬兰最著名的艺术博物馆。',
    lat: 60.1699,
    lng: 24.9384,
    type: 'art',
    continent: 'Europe',
    country: 'Finland',
    city: 'Helsinki',
    foundedYear: 1882,
    popularity: 79,
    annualVisitors: 500000,
    highlights: ['芬兰艺术', '油画', '雕塑'],
    openingHours: '周二、周四至周日 10:00-17:00；周三 10:00-20:00',
    website: 'https://www.ateneum.fi',
  },
  {
    id: 'dublin-museum',
    name: 'National Gallery of Ireland',
    nameLocal: '爱尔兰国家美术馆',
    description: '爱尔兰最重要的艺术博物馆。',
    lat: 53.3418,
    lng: -6.2558,
    type: 'art',
    continent: 'Europe',
    country: 'Ireland',
    city: 'Dublin',
    foundedYear: 1864,
    popularity: 81,
    annualVisitors: 800000,
    highlights: ['爱尔兰艺术', '欧洲绘画', '杰克·巴特勒·叶芝'],
    openingHours: '周一至周六 9:00-17:30；周日 11:00-17:30',
    website: 'https://www.nationalgallery.ie',
  },
  {
    id: 'brussels-museum',
    name: 'Royal Museums of Fine Arts',
    nameLocal: '布鲁塞尔皇家美术博物馆',
    description: '比利时最重要的艺术博物馆。',
    lat: 50.8423,
    lng: 4.3602,
    type: 'art',
    continent: 'Europe',
    country: 'Belgium',
    city: 'Brussels',
    foundedYear: 1801,
    popularity: 82,
    annualVisitors: 700000,
    highlights: ['勃鲁盖尔', '鲁本斯', '达利'],
    openingHours: '周二至周日 10:00-17:00',
    website: 'https://www.fine-arts-museum.be',
  },
  {
    id: 'warsaw-museum',
    name: 'National Museum Warsaw',
    nameLocal: '华沙国家博物馆',
    description: '波兰最大的艺术博物馆之一。',
    lat: 52.2324,
    lng: 21.0190,
    type: 'art',
    continent: 'Europe',
    country: 'Poland',
    city: 'Warsaw',
    foundedYear: 1862,
    popularity: 79,
    annualVisitors: 500000,
    highlights: ['波兰艺术', '欧洲绘画', '古代艺术'],
    openingHours: '周二至周日 10:00-18:00；周四至20:00',
    website: 'https://www.museum Warsaw.pl',
  },
  {
    id: 'athens-national-museum',
    name: 'National Archaeological Museum',
    nameLocal: '雅典国家考古博物馆',
    description: '世界上最重要的考古博物馆之一。',
    lat: 37.9856,
    lng: 23.7279,
    type: 'archaeology',
    continent: 'Europe',
    country: 'Greece',
    city: 'Athens',
    foundedYear: 1889,
    popularity: 90,
    annualVisitors: 1200000,
    highlights: ['阿伽门农黄金面具', '宙斯雕塑', '古希腊陶器'],
    openingHours: '每日 8:00-20:00',
    website: 'https://www.namuseum.gr',
  },
  {
    id: 'istanbul-archaeology',
    name: 'Istanbul Archaeology Museums',
    nameLocal: '伊斯坦布尔考古博物馆',
    description: '土耳其最大的考古博物馆群。',
    lat: 41.0056,
    lng: 28.9833,
    type: 'archaeology',
    continent: 'Europe',
    country: 'Turkey',
    city: 'Istanbul',
    foundedYear: 1891,
    popularity: 84,
    annualVisitors: 600000,
    highlights: ['亚历山大石棺', '伊斯坦布尔历史', '赫梯文物'],
    openingHours: '周三至周一 9:00-19:00',
    website: 'https://www.istanbulkultur.gov.tr',
  },
  {
    id: 'st-petersburg-anthropology',
    name: 'Kunstkamera',
    nameLocal: ' Kunstkamera人类学博物馆',
    description: '俄罗斯第一个人类学博物馆，由彼得大帝创立。',
    lat: 59.9415,
    lng: 30.3108,
    type: 'anthropology',
    continent: 'Europe',
    country: 'Russia',
    city: 'Saint Petersburg',
    foundedYear: 1727,
    popularity: 76,
    annualVisitors: 300000,
    highlights: ['人类学收藏', '彼得大帝藏品', '部落文物'],
    openingHours: '周三至周日 11:00-18:00',
    website: 'https://www.kunstkamera.ru',
  },
  {
    id: 'moscow-history',
    name: 'State Historical Museum',
    nameLocal: '俄罗斯国家历史博物馆',
    description: '莫斯科最重要的历史博物馆。',
    lat: 55.7539,
    lng: 37.6208,
    type: 'history',
    continent: 'Europe',
    country: 'Russia',
    city: 'Moscow',
    foundedYear: 1872,
    popularity: 87,
    annualVisitors: 1500000,
    highlights: ['俄罗斯历史', '沙皇珍宝', '古代俄罗斯'],
    openingHours: '周三至周一 10:00-18:00',
    website: 'https://www.shm.ru',
  },

  // 中东博物馆 (归类为亚洲)
  {
    id: 'iran-national-museum',
    name: 'National Museum of Iran',
    nameLocal: '伊朗国家博物馆',
    description: '伊朗最大的考古和历史博物馆。',
    lat: 35.6892,
    lng: 51.3890,
    type: 'history',
    continent: 'Asia',
    country: 'Iran',
    city: 'Tehran',
    foundedYear: 1937,
    popularity: 82,
    annualVisitors: 500000,
    highlights: ['波斯文物', '阿契美尼德艺术', '伊斯兰艺术'],
    openingHours: '周六至周四 9:00-16:30',
    website: 'https://www.iranmuseum.ir',
  },
  {
    id: 'dubai-museum',
    name: 'Dubai Museum',
    nameLocal: '迪拜博物馆',
    description: '展示迪拜历史和文化的博物馆。',
    lat: 25.2697,
    lng: 55.3094,
    type: 'history',
    continent: 'Asia',
    country: 'UAE',
    city: 'Dubai',
    foundedYear: 1971,
    popularity: 85,
    annualVisitors: 800000,
    highlights: ['考古文物', '传统生活展', '水下考古'],
    openingHours: '周六至周四 8:30-20:30；周五 15:00-20:30',
    website: 'https://www.dubaiculture.gov.ae',
  },
  {
    id: 'abu-dhabi-museum',
    name: 'Louvre Abu Dhabi',
    nameLocal: '阿布扎比卢浮宫',
    description: '阿布扎比的世界级艺术博物馆，由法国卢浮宫合作建设。',
    lat: 24.5344,
    lng: 54.5372,
    type: 'art',
    continent: 'Asia',
    country: 'UAE',
    city: 'Abu Dhabi',
    foundedYear: 2017,
    popularity: 90,
    annualVisitors: 1000000,
    highlights: ['跨文明艺术', '达芬奇作品', '古代文明'],
    openingHours: '周三至周一 10:00-20:00',
    website: 'https://www.louvreabudhabi.ae',
  },
  {
    id: 'saudi-national-museum',
    name: 'National Museum of Saudi Arabia',
    nameLocal: '沙特阿拉伯国家博物馆',
    description: '展示沙特阿拉伯历史和伊斯兰文明的博物馆。',
    lat: 24.6333,
    lng: 46.7167,
    type: 'history',
    continent: 'Asia',
    country: 'Saudi Arabia',
    city: 'Riyadh',
    foundedYear: 1999,
    popularity: 83,
    annualVisitors: 500000,
    highlights: ['伊斯兰艺术', '沙特历史', '考古文物'],
    openingHours: '周六至周四 9:00-20:00；周五 16:00-20:00',
    website: 'https://www.sauditourism.sa',
  },
  {
    id: 'israel-museum',
    name: 'Israel Museum',
    nameLocal: '以色列博物馆',
    description: '以色列最大的综合性博物馆。',
    lat: 31.7683,
    lng: 35.2137,
    type: 'history',
    continent: 'Asia',
    country: 'Israel',
    city: 'Jerusalem',
    foundedYear: 1965,
    popularity: 86,
    annualVisitors: 900000,
    highlights: ['死海古卷', '圣经手稿', '犹太艺术'],
    openingHours: '周一、周三至周六 10:00-17:00；周二 16:00-21:00；周日 10:00-14:00',
    website: 'https://www.imj.org.il',
  },
  {
    id: 'amman-museum',
    name: 'Jordan Archaeological Museum',
    nameLocal: '约旦考古博物馆',
    description: '约旦最重要的考古博物馆。',
    lat: 31.9454,
    lng: 35.9284,
    type: 'archaeology',
    continent: 'Asia',
    country: 'Jordan',
    city: 'Amman',
    foundedYear: 1955,
    popularity: 78,
    annualVisitors: 400000,
    highlights: ['佩特拉文物', '死海古卷复制品', '新石器时代展'],
    openingHours: '每日 8:00-18:00',
    website: 'https://www.jordanmuseum.jo',
  },
  {
    id: 'cairo-museum',
    name: 'Egyptian Museum',
    nameLocal: '埃及博物馆',
    description: '世界上最重要的埃及文物博物馆。',
    lat: 30.0478,
    lng: 31.2336,
    type: 'archaeology',
    continent: 'Africa',
    country: 'Egypt',
    city: 'Cairo',
    foundedYear: 1902,
    popularity: 93,
    annualVisitors: 2500000,
    highlights: ['图坦卡蒙黄金面具', '木乃伊室', '皇家珠宝'],
    openingHours: '每日 9:00-17:00',
    website: 'https://www.egyptianmuseum.org',
  },
  {
    id: 'tunis-museum',
    name: 'Bardo Museum',
    nameLocal: '巴尔杜博物馆',
    description: '北非最重要的博物馆之一，以罗马马赛克闻名。',
    lat: 36.8499,
    lng: 10.1670,
    type: 'archaeology',
    continent: 'Africa',
    country: 'Tunisia',
    city: 'Tunis',
    foundedYear: 1888,
    popularity: 80,
    annualVisitors: 500000,
    highlights: ['罗马马赛克', '腓尼基文物', '伊斯兰艺术'],
    openingHours: '周三至周一 10:00-17:00',
    website: 'https://www.bardomuseum.tn',
  },
  {
    id: 'marrakech-museum',
    name: 'Marrakech Museum',
    nameLocal: '马拉喀什博物馆',
    description: '摩洛哥最重要的艺术和历史博物馆之一。',
    lat: 31.6295,
    lng: -7.9811,
    type: 'art',
    continent: 'Africa',
    country: 'Morocco',
    city: 'Marrakech',
    foundedYear: 1997,
    popularity: 76,
    annualVisitors: 300000,
    highlights: ['摩洛哥艺术', '传统手工艺', '伊斯兰艺术'],
    openingHours: '每日 9:00-18:00',
    website: 'https://www.marrakechmuseum.org',
  },

  // 更多日本博物馆
  {
    id: 'kyoto-national-museum',
    name: 'Kyoto National Museum',
    nameLocal: '京都国立博物馆',
    description: '日本重要的国立博物馆，收藏古代美术和工艺品。',
    lat: 34.9931,
    lng: 135.6723,
    type: 'art',
    continent: 'Asia',
    country: 'Japan',
    city: 'Kyoto',
    foundedYear: 1897,
    popularity: 82,
    annualVisitors: 600000,
    highlights: ['平安京遗产', '日本陶瓷', '和服收藏'],
    openingHours: '周二至周日 9:30-18:00',
    website: 'https://www.knhm.jp',
  },
  {
    id: 'ghibli-museum',
    name: 'Ghibli Museum',
    nameLocal: '三鹰之森吉卜力美术馆',
    description: '展示吉卜力动画工作室作品的博物馆。',
    lat: 35.6965,
    lng: 139.5704,
    type: 'specialized',
    continent: 'Asia',
    country: 'Japan',
    city: 'Mitaka',
    foundedYear: 2001,
    popularity: 92,
    annualVisitors: 800000,
    highlights: ['龙猫', '天空之城', '吉卜力原画'],
    openingHours: '每日 10:00-18:00',
    website: 'https://www.ghibli-museum.jp',
  },
  {
    id: 'naoshima-contemporary',
    name: 'Benesse House',
    nameLocal: '直岛倍乐生之家',
    description: '位于直岛的艺术酒店和美术馆，展示现代艺术。',
    lat: 34.4475,
    lng: 133.9861,
    type: 'art',
    continent: 'Asia',
    country: 'Japan',
    city: 'Naoshima',
    foundedYear: 1992,
    popularity: 85,
    annualVisitors: 700000,
    highlights: ['草间弥生', '安藤忠雄建筑', '现代艺术'],
    openingHours: '每日 8:00-21:00',
    website: 'https://www.benesse.co.jp',
  },
  {
    id: 'edogawa-museum',
    name: 'Edo-Tokyo Museum',
    nameLocal: '江户东京博物馆',
    description: '展示东京江户时代历史文化的博物馆。',
    lat: 35.7148,
    lng: 139.7967,
    type: 'history',
    continent: 'Asia',
    country: 'Japan',
    city: 'Tokyo',
    foundedYear: 1993,
    popularity: 83,
    annualVisitors: 800000,
    highlights: ['江户城', '浮世绘', '传统工艺'],
    openingHours: '周二至周日 9:30-17:30',
    website: 'https://www.edo-tokyo-museum.or.jp',
  },
  {
    id: 'sumida-museum',
    name: 'Sumida Hokusai Museum',
    nameLocal: '墨田北斋美术馆',
    description: '展示浮世绘大师葛饰北斋作品的专门博物馆。',
    lat: 35.7102,
    lng: 139.8007,
    type: 'art',
    continent: 'Asia',
    country: 'Japan',
    city: 'Tokyo',
    foundedYear: 2016,
    popularity: 78,
    annualVisitors: 400000,
    highlights: ['浮世绘', '神奈川冲浪里', '北斋作品'],
    openingHours: '周二至周日 9:30-17:30',
    website: 'https://www.hokusai-museum.jp',
  },

  // 更多大洋洲博物馆
  {
    id: 'queensland-art-gallery',
    name: 'Queensland Art Gallery',
    nameLocal: '昆士兰艺术馆',
    description: '澳大利亚重要的现代艺术博物馆。',
    lat: -27.4713,
    lng: 153.0156,
    type: 'art',
    continent: 'Oceania',
    country: 'Australia',
    city: 'Brisbane',
    foundedYear: 1896,
    popularity: 80,
    annualVisitors: 800000,
    highlights: ['亚太艺术', '当代艺术', '原住民艺术'],
    openingHours: '每日 10:00-17:00',
    website: 'https://www.qagoma.qld.gov.au',
  },
  {
    id: 'art-gallery-nsw',
    name: 'Art Gallery of New South Wales',
    nameLocal: '新南威尔士艺术馆',
    description: '澳大利亚最重要的艺术博物馆之一。',
    lat: -33.8686,
    lng: 151.2350,
    type: 'art',
    continent: 'Oceania',
    country: 'Australia',
    city: 'Sydney',
    foundedYear: 1871,
    popularity: 83,
    annualVisitors: 1100000,
    highlights: ['欧洲艺术', '亚洲艺术', '澳大利亚艺术'],
    openingHours: '每日 10:00-17:00',
    website: 'https://www.artgallery.nsw.gov.au',
  },
  {
    id: 'western-australian-museum',
    name: 'Western Australian Museum',
    nameLocal: '西澳大利亚博物馆',
    description: '展示西澳大利亚自然和文化遗产。',
    lat: -31.9535,
    lng: 115.8570,
    type: 'natural-history',
    continent: 'Oceania',
    country: 'Australia',
    city: 'Perth',
    foundedYear: 1892,
    popularity: 76,
    annualVisitors: 500000,
    highlights: ['恐龙化石', '原住民文化', '西澳自然'],
    openingHours: '每日 10:00-17:00',
    website: 'https://www.museum.wa.gov.au',
  },
  {
    id: 'auckland-war-memorial',
    name: 'Auckland War Memorial Museum',
    nameLocal: '奥克兰战争纪念博物馆',
    description: '新西兰最重要的战争和历史博物馆。',
    lat: -36.8586,
    lng: 174.7627,
    type: 'history',
    continent: 'Oceania',
    country: 'New Zealand',
    city: 'Auckland',
    foundedYear: 1852,
    popularity: 80,
    annualVisitors: 500000,
    highlights: ['战争历史', '毛利文化', '太平洋岛屿文物'],
    openingHours: '每日 10:00-17:00',
    website: 'https://www.aucklandmuseum.com',
  },
  {
    id: 'canberra-museum',
    name: 'National Museum of Australia',
    nameLocal: '澳大利亚国家博物馆',
    description: '展示澳大利亚历史和文化的国家博物馆。',
    lat: -35.2937,
    lng: 149.1201,
    type: 'history',
    continent: 'Oceania',
    country: 'Australia',
    city: 'Canberra',
    foundedYear: 2001,
    popularity: 79,
    annualVisitors: 450000,
    highlights: ['澳大利亚历史', '原住民艺术', '社会历史'],
    openingHours: '每日 9:00-17:00',
    website: 'https://www.nma.gov.au',
  },
  {
    id: 'christchurch-museum',
    name: 'Christchurch Art Gallery',
    nameLocal: '基督城艺术馆',
    description: '新西兰南岛最大的艺术博物馆。',
    lat: -43.5321,
    lng: 172.6302,
    type: 'art',
    continent: 'Oceania',
    country: 'New Zealand',
    city: 'Christchurch',
    foundedYear: 2003,
    popularity: 74,
    annualVisitors: 300000,
    highlights: ['新西兰艺术', '欧洲艺术', '当代艺术'],
    openingHours: '每日 10:00-17:00',
    website: 'https://christchurchartgallery.org.nz',
  },
  {
    id: 'tasmania-museum',
    name: 'Tasmanian Museum and Art Gallery',
    nameLocal: '塔斯马尼亚博物馆和艺术馆',
    description: '澳大利亚塔斯马尼亚的文化艺术中心。',
    lat: -42.8819,
    lng: 147.3262,
    type: 'history',
    continent: 'Oceania',
    country: 'Australia',
    city: 'Hobart',
    foundedYear: 1852,
    popularity: 73,
    annualVisitors: 350000,
    highlights: ['殖民历史', '塔斯马尼亚自然', '艺术收藏'],
    openingHours: '每日 10:00-17:00',
    website: 'https://www.tmag.tas.gov.au',
  },

  // 更多非洲博物馆
  {
    id: 'ethnographic-museum',
    name: 'National Museum of Ethiopia',
    nameLocal: '埃塞俄比亚国家博物馆',
    description: '展示埃塞俄比亚丰富历史文化的博物馆。',
    lat: 9.0054,
    lng: 38.7636,
    type: 'history',
    continent: 'Africa',
    country: 'Ethiopia',
    city: 'Addis Ababa',
    foundedYear: 1944,
    popularity: 76,
    annualVisitors: 200000,
    highlights: ['露西化石', '埃塞俄比亚历史', '宗教艺术'],
    openingHours: '周二至周日 9:00-17:00',
  },
  {
    id: 'dakar-museum',
    name: 'Museum of Black Civilizations',
    nameLocal: '黑人文明博物馆',
    description: '塞内加尔展示非洲文明的重要博物馆。',
    lat: 14.6928,
    lng: -17.4467,
    type: 'cultural',
    continent: 'Africa',
    country: 'Senegal',
    city: 'Dakar',
    foundedYear: 2018,
    popularity: 78,
    annualVisitors: 300000,
    highlights: ['非洲艺术', '黑人历史', '文化遗产'],
    openingHours: '周三至周一 10:00-18:00',
  },
  {
    id: 'lagos-museum',
    name: 'National Museum Nigeria',
    nameLocal: '尼日利亚国家博物馆',
    description: '西非最大的博物馆，展示尼日利亚文化遗产。',
    lat: 6.4531,
    lng: 3.3958,
    type: 'history',
    continent: 'Africa',
    country: 'Nigeria',
    city: 'Lagos',
    foundedYear: 1957,
    popularity: 72,
    annualVisitors: 200000,
    highlights: ['尼日利亚艺术', '部落文物', '考古发现'],
    openingHours: '周一至周六 9:00-18:00',
  },
  {
    id: 'accra-museum',
    name: 'National Museum Ghana',
    nameLocal: '加纳国家博物馆',
    description: '展示加纳和西非文化遗产的重要博物馆。',
    lat: 5.5557,
    lng: -0.1873,
    type: 'history',
    continent: 'Africa',
    country: 'Ghana',
    city: 'Accra',
    foundedYear: 1957,
    popularity: 70,
    annualVisitors: 150000,
    highlights: ['阿散蒂王国', '黄金制品', '部落文物'],
    openingHours: '每日 9:00-17:00',
  },
  {
    id: 'dar-es-salaam-museum',
    name: 'National Museum Tanzania',
    nameLocal: '坦桑尼亚国家博物馆',
    description: '展示东非历史和人类起源的博物馆。',
    lat: -6.7923,
    lng: 39.2083,
    type: 'history',
    continent: 'Africa',
    country: 'Tanzania',
    city: 'Dar es Salaam',
    foundedYear: 1934,
    popularity: 73,
    annualVisitors: 180000,
    highlights: ['人类起源', '塞伦盖蒂文物', '桑给巴尔历史'],
    openingHours: '每日 9:00-17:00',
  },
  {
    id: 'johannesburg-art',
    name: 'Johannesburg Art Gallery',
    nameLocal: '约翰内斯堡艺术馆',
    description: '南非最大的艺术博物馆之一。',
    lat: -26.2054,
    lng: 28.0462,
    type: 'art',
    continent: 'Africa',
    country: 'South Africa',
    city: 'Johannesburg',
    foundedYear: 1910,
    popularity: 74,
    annualVisitors: 300000,
    highlights: ['南非艺术', '非洲艺术', '国际收藏'],
    openingHours: '周二至周日 10:00-17:00',
  },
  {
    id: 'mali-museum',
    name: 'Mali National Museum',
    nameLocal: '马里国家博物馆',
    description: '展示西非古文明的重要博物馆。',
    lat: 12.6392,
    lng: -8.0029,
    type: 'history',
    continent: 'Africa',
    country: 'Mali',
    city: 'Bamako',
    foundedYear: 1957,
    popularity: 68,
    annualVisitors: 100000,
    highlights: ['廷巴克图文物', '苏丹艺术', '伊斯兰手稿'],
    openingHours: '每日 9:00-17:00',
  },
  {
    id: 'uganda-museum',
    name: 'Uganda Museum',
    nameLocal: '乌干达博物馆',
    description: '展示乌干达自然和文化遗产的博物馆。',
    lat: 0.3476,
    lng: 32.5825,
    type: 'natural-history',
    continent: 'Africa',
    country: 'Uganda',
    city: 'Kampala',
    foundedYear: 1908,
    popularity: 65,
    annualVisitors: 80000,
    highlights: ['乌干达历史', '部落文物', '自然标本'],
    openingHours: '每日 9:00-17:00',
  },
];

export function getMuseumsByContinent(continent: Continent): Museum[] {
  return museums.filter(m => m.continent === continent);
}

export function getMuseumsByType(type: MuseumType): Museum[] {
  return museums.filter(m => m.type === type);
}

export function getMuseumsByYearRange(startYear: number, endYear: number): Museum[] {
  return museums.filter(m => m.foundedYear >= startYear && m.foundedYear <= endYear);
}

export function searchMuseums(query: string): Museum[] {
  const lowerQuery = query.toLowerCase();
  return museums.filter(m => 
    m.name.toLowerCase().includes(lowerQuery) ||
    m.nameLocal?.toLowerCase().includes(lowerQuery) ||
    m.city.toLowerCase().includes(lowerQuery) ||
    m.country.toLowerCase().includes(lowerQuery)
  );
}

export function getMuseumById(id: string): Museum | undefined {
  return museums.find(m => m.id === id);
}

export const continents: Continent[] = ['Asia', 'Europe', 'North America', 'South America', 'Africa', 'Oceania'];
export const museumTypes: MuseumType[] = ['art', 'history', 'science', 'natural-history', 'archaeology', 'technology', 'cultural', 'military', 'maritime', 'specialized'];

export const eraRanges = [
  { label: '18世纪之前', start: 0, end: 1799 },
  { label: '19世纪', start: 1800, end: 1899 },
  { label: '20世纪上半叶', start: 1900, end: 1950 },
  { label: '20世纪下半叶', start: 1951, end: 2000 },
  { label: '21世纪', start: 2001, end: 2100 },
];
